export const errorCodes = [
  "PLATFORM.VALIDATION_FAILED", "AUTH.AUTHENTICATION_REQUIRED", "AUTH.PERMISSION_DENIED",
  "RESOURCE.NOT_FOUND", "STATE.CONFLICT", "CONCURRENCY.CONFLICT", "BUSINESS_RULE.VIOLATION",
  "PLATFORM.RATE_LIMITED", "INTERNAL.UNEXPECTED",
] as const;

export type ErrorCode = (typeof errorCodes)[number];
