import type { Prisma, PrismaClient } from "@prisma/client";
import { Prisma as PrismaNamespace } from "@prisma/client";

import { createTransactionBoundAuditRecorder, type AuditEvent } from "@/platform/audit";
import { AppError, type JsonObject } from "@/platform/errors";
import type { RequestContext } from "@/platform/request-context";
import type { Clock } from "@/platform/time";

import { partRevisionError } from "../application/errors";
import type { PartRevisionTransactionBoundary, PersistDecisionInput } from "../application/part-revision-transaction-boundary";
import type { CreatePartRevisionInput, GetPartRevisionInput, ListPartRevisionReviewsInput, ListPartRevisionsInput, PartRevisionDto, PartRevisionPage, PartRevisionReviewDto, PartRevisionReviewPage, ReleasePartRevisionInput, SubmitPartRevisionInput, UpdatePartRevisionInput } from "../domain/part-revision";

type Transaction = Prisma.TransactionClient;
type RevisionRow = Prisma.PartRevisionGetPayload<{ include: { partMaster: true; createdBy: true; releasedBy: true } }>;
type ReviewRow = Prisma.PartRevisionReviewGetPayload<{ include: { reviewer: true } }>;
const uuid = (value: unknown): value is string => typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
function actor(context: RequestContext) { if (context.actor.kind !== "user") throw new AppError({ code: "AUTH.AUTHENTICATION_REQUIRED", httpStatus: 401, internalMessage: "AUTHENTICATION_REQUIRED", publicMessage: "需要认证。" }); return context.actor; }
function pageNumber(value: number | undefined) { if (value === undefined) return 1; if (!Number.isSafeInteger(value) || value < 1) throw partRevisionError("INVALID_PART_REVISION_INPUT"); return value; }
function pageSize(value: number | undefined) { if (value === undefined) return 25; if (!Number.isSafeInteger(value) || value < 1 || value > 100) throw partRevisionError("INVALID_PART_REVISION_INPUT"); return value; }
function pageOffset(currentPage: number, currentPageSize: number) { const offset = (currentPage - 1) * currentPageSize; if (!Number.isSafeInteger(offset)) throw partRevisionError("INVALID_PART_REVISION_INPUT"); return offset; }
function dto(row: RevisionRow): PartRevisionDto { return { id: row.id, revisionNo: row.revisionNo, status: row.status, changeSummary: row.changeSummary, part: { id: row.partMaster.id, partNumber: row.partMaster.partNumber, drawingNumber: row.partMaster.drawingNumber, name: row.partMaster.name }, createdBy: { id: row.createdBy.id, username: row.createdBy.username, displayName: row.createdBy.displayName }, createdAt: row.createdAt, updatedAt: row.updatedAt, lastSubmittedAt: row.lastSubmittedAt, releasedBy: row.releasedBy ? { id: row.releasedBy.id, username: row.releasedBy.username, displayName: row.releasedBy.displayName } : null, releasedAt: row.releasedAt }; }
function reviewDto(row: ReviewRow): PartRevisionReviewDto { return { id: row.id, decision: row.decision, reviewer: { id: row.reviewer.id, username: row.reviewer.username, displayName: row.reviewer.displayName }, comment: row.comment, creatorReviewOverride: row.creatorReviewOverride, overrideReason: row.overrideReason, decidedAt: row.decidedAt }; }
// Audit retains the platform's request-arrival timestamp contract; lifecycle
// timestamps below are independently sourced from the injected Clock.
function audit(context: RequestContext, action: string, targetId: string, details: JsonObject, reason?: string) { const current = actor(context); return { actorKind: "USER" as const, actorAccountId: current.userId, actorSessionId: current.sessionId, organizationId: current.organizationId, requestId: context.requestId, action, targetType: "part_revision", targetId, details, reason, occurredAt: new Date(context.receivedAt) }; }
function recorder(tx: Transaction) { return createTransactionBoundAuditRecorder(async (event: AuditEvent) => { await tx.auditLog.create({ data: { organizationId: event.organizationId, actorKind: event.actorKind, actorAccountId: event.actorKind === "USER" ? event.actorAccountId : null, actorSessionId: event.actorKind === "USER" ? event.actorSessionId : null, requestId: event.requestId, action: event.action, targetType: event.targetType, targetId: event.targetId, reason: event.reason ?? null, details: event.details as Prisma.InputJsonValue | undefined, occurredAt: event.occurredAt } }); }); }
async function lockPart(tx: Transaction, partId: string, organizationId: string) { const rows = await tx.$queryRaw<{ id: string; status: "ACTIVE" | "INACTIVE" }[]>(PrismaNamespace.sql`SELECT id, status FROM part_master WHERE id = ${partId}::uuid AND "organizationId" = ${organizationId}::uuid FOR UPDATE`); return rows[0] ?? null; }
async function lockRevision(tx: Transaction, revisionId: string, organizationId: string) { const rows = await tx.$queryRaw<{ id: string }[]>(PrismaNamespace.sql`SELECT id FROM part_revision WHERE id = ${revisionId}::uuid AND "organizationId" = ${organizationId}::uuid FOR UPDATE`); if (!rows[0]) throw partRevisionError("PART_REVISION_NOT_FOUND"); }
async function fresh(client: PrismaClient | Transaction, revisionId: string, organizationId: string): Promise<RevisionRow> { const row = await client.partRevision.findFirst({ where: { id: revisionId, organizationId }, include: { partMaster: true, createdBy: true, releasedBy: true } }); if (!row) throw partRevisionError("PART_REVISION_NOT_FOUND"); return row; }
async function revisionOnly(tx: Transaction, revisionId: string, organizationId: string) { if (!uuid(revisionId)) throw partRevisionError("PART_REVISION_NOT_FOUND"); await lockRevision(tx, revisionId, organizationId); return fresh(tx, revisionId, organizationId); }
async function forward(tx: Transaction, revisionId: string, organizationId: string) { if (!uuid(revisionId)) throw partRevisionError("PART_REVISION_NOT_FOUND"); const reference = await tx.partRevision.findFirst({ where: { id: revisionId, organizationId }, select: { partMasterId: true } }); if (!reference) throw partRevisionError("PART_REVISION_NOT_FOUND"); if (!await lockPart(tx, reference.partMasterId, organizationId)) throw partRevisionError("PART_REVISION_NOT_FOUND"); await lockRevision(tx, revisionId, organizationId); return fresh(tx, revisionId, organizationId); }

export function createPartRevisionTransactionBoundary(prisma: PrismaClient, clock: Clock): PartRevisionTransactionBoundary { return {
  async create(input: CreatePartRevisionInput) { const current = actor(input.context); if (!uuid(input.partId)) throw partRevisionError("PART_REVISION_NOT_FOUND"); try { return await prisma.$transaction(async (tx) => { const part = await lockPart(tx, input.partId, current.organizationId); if (!part) throw partRevisionError("PART_REVISION_NOT_FOUND"); if (part.status !== "ACTIVE") throw partRevisionError("PART_MASTER_INACTIVE"); const latest = await tx.partRevision.findFirst({ where: { organizationId: current.organizationId, partMasterId: input.partId }, orderBy: { revisionNo: "desc" }, select: { revisionNo: true } }); const row = await tx.partRevision.create({ data: { organizationId: current.organizationId, partMasterId: input.partId, revisionNo: (latest?.revisionNo ?? 0) + 1, changeSummary: input.changeSummary, createdByAccountId: current.userId }, include: { partMaster: true, createdBy: true, releasedBy: true } }); await recorder(tx).record(audit(input.context, "part_revision.create", row.id, { revisionNo: row.revisionNo, partMasterId: row.partMasterId })); return dto(row); }); } catch (cause) { if ((cause as { code?: string }).code === "P2002") throw partRevisionError("PART_REVISION_UNRELEASED_EXISTS", cause); throw cause; } },
  async get(input: GetPartRevisionInput) { const current = actor(input.context); if (!uuid(input.revisionId)) throw partRevisionError("PART_REVISION_NOT_FOUND"); return dto(await fresh(prisma, input.revisionId, current.organizationId)); },
  async list(input: ListPartRevisionsInput) { const current = actor(input.context); if (!uuid(input.partId)) throw partRevisionError("PART_REVISION_NOT_FOUND"); if (!await prisma.partMaster.findFirst({ where: { id: input.partId, organizationId: current.organizationId }, select: { id: true } })) throw partRevisionError("PART_REVISION_NOT_FOUND"); const currentPage = pageNumber(input.page); const currentPageSize = pageSize(input.pageSize); const where = { organizationId: current.organizationId, partMasterId: input.partId, ...(input.status ? { status: input.status } : {}) }; const [total, rows] = await prisma.$transaction([prisma.partRevision.count({ where }), prisma.partRevision.findMany({ where, orderBy: { revisionNo: "desc" }, skip: pageOffset(currentPage, currentPageSize), take: currentPageSize, include: { partMaster: true, createdBy: true, releasedBy: true } })]); return { items: rows.map(dto), page: currentPage, pageSize: currentPageSize, total } satisfies PartRevisionPage; },
  async update(input: UpdatePartRevisionInput) { const current = actor(input.context); return prisma.$transaction(async (tx) => { const row = await revisionOnly(tx, input.revisionId, current.organizationId); if (row.status !== "DRAFT" && row.status !== "RETURNED") throw partRevisionError("PART_REVISION_INVALID_TRANSITION"); if (row.changeSummary === input.changeSummary) return dto(row); const updated = await tx.partRevision.update({ where: { id: row.id }, data: { changeSummary: input.changeSummary }, include: { partMaster: true, createdBy: true, releasedBy: true } }); await recorder(tx).record(audit(input.context, "part_revision.update", updated.id, { changed: { changeSummary: input.changeSummary } })); return dto(updated); }); },
  async submit(input: SubmitPartRevisionInput) { const current = actor(input.context); return prisma.$transaction(async (tx) => { const row = await forward(tx, input.revisionId, current.organizationId); if (row.partMaster.status !== "ACTIVE") throw partRevisionError("PART_MASTER_INACTIVE"); if (row.status !== "DRAFT" && row.status !== "RETURNED") throw partRevisionError("PART_REVISION_INVALID_TRANSITION"); const mutationAt = clock.now(); const updated = await tx.partRevision.update({ where: { id: row.id }, data: { status: "REVIEWING", lastSubmittedAt: mutationAt }, include: { partMaster: true, createdBy: true, releasedBy: true } }); await recorder(tx).record(audit(input.context, "part_revision.submit_review", updated.id, { revisionNo: updated.revisionNo, fromStatus: row.status, toStatus: "REVIEWING" })); return dto(updated); }); },
  async getReviewTarget(context: RequestContext, revisionId: string) { const current = actor(context); if (!uuid(revisionId)) throw partRevisionError("PART_REVISION_NOT_FOUND"); const row = await prisma.partRevision.findFirst({ where: { id: revisionId, organizationId: current.organizationId }, select: { createdByAccountId: true } }); if (!row) throw partRevisionError("PART_REVISION_NOT_FOUND"); return row; },
  async decide(input: PersistDecisionInput) { const current = actor(input.context); return prisma.$transaction(async (tx) => { const row = input.decision === "RETURNED" ? await revisionOnly(tx, input.revisionId, current.organizationId) : await forward(tx, input.revisionId, current.organizationId); if (input.decision === "APPROVED" && row.partMaster.status !== "ACTIVE") throw partRevisionError("PART_MASTER_INACTIVE"); if (row.status !== "REVIEWING") throw partRevisionError("PART_REVISION_INVALID_TRANSITION"); const collision = row.createdByAccountId === current.userId; if (collision !== input.creatorReviewOverride) throw partRevisionError(collision ? "PART_REVISION_CREATOR_REVIEW_FORBIDDEN" : "PART_REVISION_OVERRIDE_NOT_APPLICABLE"); const mutationAt = clock.now(); const review = await tx.partRevisionReview.create({ data: { organizationId: current.organizationId, partRevisionId: row.id, reviewerAccountId: current.userId, decision: input.decision, comment: input.comment, creatorReviewOverride: input.creatorReviewOverride, overrideReason: input.overrideReason, decidedAt: mutationAt } }); const status = input.decision === "RETURNED" ? "RETURNED" : "APPROVED"; const updated = await tx.partRevision.update({ where: { id: row.id }, data: { status }, include: { partMaster: true, createdBy: true, releasedBy: true } }); await recorder(tx).record(audit(input.context, input.decision === "RETURNED" ? "part_revision.return" : "part_revision.approve", updated.id, { revisionNo: updated.revisionNo, fromStatus: "REVIEWING", toStatus: status, reviewId: review.id, creatorReviewOverride: input.creatorReviewOverride }, input.overrideReason ?? undefined)); return dto(updated); }); },
  async release(input: ReleasePartRevisionInput) { const current = actor(input.context); return prisma.$transaction(async (tx) => { const row = await forward(tx, input.revisionId, current.organizationId); if (row.partMaster.status !== "ACTIVE") throw partRevisionError("PART_MASTER_INACTIVE"); if (row.status !== "APPROVED") throw partRevisionError("PART_REVISION_INVALID_TRANSITION"); const mutationAt = clock.now(); const updated = await tx.partRevision.update({ where: { id: row.id }, data: { status: "RELEASED", releasedByAccountId: current.userId, releasedAt: mutationAt }, include: { partMaster: true, createdBy: true, releasedBy: true } }); await recorder(tx).record(audit(input.context, "part_revision.release", updated.id, { revisionNo: updated.revisionNo, fromStatus: "APPROVED", toStatus: "RELEASED", releasedAt: mutationAt.toISOString() })); return dto(updated); }); },
  async listReviews(input: ListPartRevisionReviewsInput) { const current = actor(input.context); if (!uuid(input.revisionId)) throw partRevisionError("PART_REVISION_NOT_FOUND"); await fresh(prisma, input.revisionId, current.organizationId); const currentPage = pageNumber(input.page); const currentPageSize = pageSize(input.pageSize); const where = { organizationId: current.organizationId, partRevisionId: input.revisionId }; const [total, rows] = await prisma.$transaction([prisma.partRevisionReview.count({ where }), prisma.partRevisionReview.findMany({ where, orderBy: [{ decidedAt: "asc" }, { id: "asc" }], skip: pageOffset(currentPage, currentPageSize), take: currentPageSize, include: { reviewer: true } })]); return { items: rows.map(reviewDto), page: currentPage, pageSize: currentPageSize, total } satisfies PartRevisionReviewPage; },
}; }
