"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";

interface OrgUnit { id: string; code: string; name: string; status: "ACTIVE" | "INACTIVE"; }
interface Account { id: string; username: string; displayName: string; status: "ACTIVE" | "INACTIVE" | "LOCKED"; primaryOrgUnitId: string; primaryOrgUnit?: OrgUnit; }
interface Assignment { id: string; role: string; scopeOrgUnitId: string; }
interface AccountFilters { search: string; status: string; orgUnitId: string; }
const roles = ["ADMIN", "QUALITY_MANAGER", "INSPECTOR", "ENGINEER", "VIEWER"];
const emptyFilters: AccountFilters = { search: "", status: "", orgUnitId: "" };

async function json(response: Response) { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body?.error?.message === "string" ? body.error.message : "请求失败。"); return body; }

export function UserList() {
  const [items, setItems] = useState<Account[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [filters, setFilters] = useState<AccountFilters>(emptyFilters);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ page: String(page), pageSize: "25" }); for (const [key, value] of Object.entries(filters)) if (value) params.set(key, value); const body = await json(await fetch(`/api/admin/accounts?${params}`)); setItems(body.items); setTotal(body.total); } catch (cause) { setError(cause instanceof Error ? cause.message : "加载失败。"); } finally { setLoading(false); } }, [filters, page]);
  useEffect(() => { const timeout = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timeout); }, [load]);
  return <section className="panel"><div className="toolbar"><h2>账户</h2><Link className="button" href="/admin/users/new">创建账户</Link></div><form className="filters" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setPage(1); setFilters({ search: String(data.get("search") ?? ""), status: String(data.get("status") ?? ""), orgUnitId: String(data.get("orgUnitId") ?? "") }); }}><input name="search" placeholder="用户名或显示名"/><select name="status"><option value="">全部状态</option><option>ACTIVE</option><option>INACTIVE</option><option>LOCKED</option></select><input name="orgUnitId" placeholder="OrgUnit UUID（可选）"/><button>筛选</button></form>{error && <p className="error">{error}</p>}{loading ? <p>加载中…</p> : items.length === 0 ? <p>没有符合条件的账户。</p> : <div className="table-wrap"><table><thead><tr><th>用户名</th><th>显示名</th><th>主组织单元</th><th>状态</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.username}</td><td>{item.displayName}</td><td>{item.primaryOrgUnit?.name ?? item.primaryOrgUnitId}</td><td><span className={`badge ${item.status.toLowerCase()}`}>{item.status}</span></td><td><Link href={`/admin/users/${item.id}`}>管理</Link></td></tr>)}</tbody></table></div>}<div className="pager"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>上一页</button><span>第 {page} 页 · {total} 条</span><button disabled={page * 25 >= total} onClick={() => setPage((value) => value + 1)}>下一页</button></div></section>;
}

export function NewUser() {
  const [units, setUnits] = useState<OrgUnit[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/admin/org-units?activeOnly=true").then(json).then((body) => setUnits(body.orgUnits)).catch((cause) => setError(cause.message)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); try { const body = await json(await fetch("/api/admin/accounts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(data)) })); setMessage("账户已创建；当前没有任何 Role Assignment。"); window.setTimeout(() => window.location.assign(`/admin/users/${body.account.id}`), 500); } catch (cause) { setError(cause instanceof Error ? cause.message : "创建失败。"); } }
  return <section className="panel narrow"><h2>创建账户</h2><form className="form-stack" onSubmit={submit}><label>用户名<input name="username" required /></label><label>显示名<input name="displayName" required /></label><label>主组织单元（组织身份）<select name="primaryOrgUnitId" required><option value="">请选择</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.code} · {unit.name}</option>)}</select></label><label>密码（15–128 字符）<input name="password" type="password" minLength={15} maxLength={128} required /></label><button>创建</button>{message && <p role="status">{message}</p>}{error && <p className="error">{error}</p>}</form></section>;
}

export function UserDetail({ accountId }: { readonly accountId: string }) {
  const [account, setAccount] = useState<Account | null>(null); const [units, setUnits] = useState<OrgUnit[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const [accountBody, unitBody, roleBody] = await Promise.all([fetch(`/api/admin/accounts/${accountId}`).then(json), fetch("/api/admin/org-units").then(json), fetch(`/api/admin/accounts/${accountId}/role-assignments`).then(json)]); setAccount(accountBody.account); setUnits(unitBody.orgUnits); setAssignments(roleBody.assignments); } catch (cause) { setError(cause instanceof Error ? cause.message : "加载失败。"); } }, [accountId]);
  useEffect(() => { const timeout = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timeout); }, [load]);
  async function act(url: string, method: string, body?: unknown) { setError(""); setMessage(""); try { await json(await fetch(url, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined })); setMessage("操作成功。"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失败。"); } }
  if (!account) return <section className="panel"><p>{error || "加载中…"}</p></section>;
  return <div className="split"><section className="panel"><h2>账户资料</h2><p><strong>用户名：</strong>{account.username}（不可修改）</p><form className="form-stack" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void act(`/api/admin/accounts/${accountId}`, "PATCH", { displayName: data.get("displayName"), primaryOrgUnitId: data.get("primaryOrgUnitId") }); }}><label>显示名<input name="displayName" defaultValue={account.displayName} required /></label><label>主组织单元（组织身份）<select name="primaryOrgUnitId" defaultValue={account.primaryOrgUnitId}>{units.map((unit) => <option key={unit.id} value={unit.id} disabled={unit.status !== "ACTIVE"}>{unit.code} · {unit.name}{unit.status !== "ACTIVE" ? "（历史/停用）" : ""}</option>)}</select></label><button>保存资料</button></form><h3>账户状态</h3><div className="button-row">{["ACTIVE", "INACTIVE", "LOCKED"].map((status) => <button key={status} disabled={account.status === status} onClick={() => void act(`/api/admin/accounts/${accountId}/status`, "PATCH", { status })}>{status}</button>)}</div><h3>管理员重置密码</h3><form className="inline-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void act(`/api/admin/accounts/${accountId}/reset-password`, "POST", { newPassword: data.get("newPassword") }); event.currentTarget.reset(); }}><input name="newPassword" type="password" minLength={15} maxLength={128} placeholder="新密码" required/><button>重置</button></form></section><section className="panel"><h2>Role Assignments</h2><p className="hint">Role scope 是授权锚点，与上方主组织单元相互独立。</p>{assignments.length === 0 ? <p>当前无 Role Assignment。</p> : <ul className="list">{assignments.map((item) => <li key={item.id}><span><strong>{item.role}</strong><br/><small>scope: {units.find((unit) => unit.id === item.scopeOrgUnitId)?.name ?? item.scopeOrgUnitId}</small></span><button onClick={() => void act(`/api/admin/role-assignments/${item.id}`, "DELETE")}>撤销</button></li>)}</ul>}<form className="form-stack" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void act(`/api/admin/accounts/${accountId}/role-assignments`, "POST", { role: data.get("role"), scopeOrgUnitId: data.get("scopeOrgUnitId") }); }}><label>Role<select name="role">{roles.map((role) => <option key={role}>{role}</option>)}</select></label><label>授权 scope OrgUnit<select name="scopeOrgUnitId" required><option value="">请选择</option>{units.filter((unit) => unit.status === "ACTIVE").map((unit) => <option key={unit.id} value={unit.id}>{unit.code} · {unit.name}</option>)}</select></label><button>分配 Role</button></form>{message && <p role="status">{message}</p>}{error && <p className="error">{error}</p>}</section></div>;
}
