"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { formatInstantForBusinessDisplay } from "@/platform/time";

export interface Category { id: string; name: string; status: "ACTIVE" | "INACTIVE"; }
interface Part { id: string; partNumber: string; drawingNumber: string | null; name: string; description: string | null; status: "ACTIVE" | "INACTIVE"; category: Category; updatedAt: string; }

export const CATEGORY_PAGE_SIZE = 100;

export function ensureCurrentCategory(categories: readonly Category[], current: Category): Category[] {
  return categories.some((category) => category.id === current.id) ? [...categories] : [current, ...categories];
}

export function canLoadMoreCategories(total: number, loaded: number): boolean { return loaded < total; }

export function appendCategories(current: readonly Category[], next: readonly Category[]): Category[] {
  const ids = new Set(current.map((category) => category.id));
  return [...current, ...next.filter((category) => !ids.has(category.id))];
}

export function preserveCategoryId(currentId: string, selected: FormDataEntryValue | null): string {
  return typeof selected === "string" && selected.length > 0 ? selected : currentId;
}

async function json(response: Response) { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body?.error?.message === "string" ? body.error.message : "请求失败。"); return body; }

export function PartsList({ canCreate = false }: { readonly canCreate?: boolean }) {
  const [items, setItems] = useState<Part[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [categoryTotal, setCategoryTotal] = useState(0); const [categoryPage, setCategoryPage] = useState(1); const [filters, setFilters] = useState({ search: "", categoryId: "", status: "" }); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const loadCategories = useCallback(async (nextPage: number, append: boolean) => { try { const body = await json(await fetch(`/api/part-categories?page=${nextPage}&pageSize=${CATEGORY_PAGE_SIZE}`)); setCategories((current) => append ? appendCategories(current, body.items) : body.items); setCategoryTotal(body.total); setCategoryPage(nextPage); } catch { /* the parts list remains usable when category filters are unavailable */ } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void loadCategories(1, false); }, 0); return () => window.clearTimeout(timer); }, [loadCategories]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ page: String(page), pageSize: "25" }); for (const [key, value] of Object.entries(filters)) if (value) params.set(key, value); const body = await json(await fetch(`/api/parts?${params}`)); setItems(body.items); setTotal(body.total); } catch (cause) { setError(cause instanceof Error ? cause.message : "加载失败。"); } finally { setLoading(false); } }, [filters, page]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setPage(1); setFilters({ search: String(data.get("search") ?? ""), categoryId: String(data.get("categoryId") ?? ""), status: String(data.get("status") ?? "") }); }
  return <section className="panel"><div className="toolbar"><h1>零件主数据</h1><div>{canCreate && <Link className="button" href="/parts/new">新建零件</Link>}{" "}<Link className="button" href="/parts/categories">类别管理</Link></div></div><form className="filters" onSubmit={submit}><input name="search" placeholder="零件编号、图号或名称"/><select name="categoryId"><option value="">全部类别</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select>{canLoadMoreCategories(categoryTotal, categories.length) && <button type="button" onClick={() => void loadCategories(categoryPage + 1, true)}>加载更多类别</button>}<select name="status"><option value="">全部状态</option><option>ACTIVE</option><option>INACTIVE</option></select><button>筛选</button></form>{error && <p className="error">{error}</p>}{loading ? <p>加载中…</p> : items.length === 0 ? <p>没有符合条件的零件。</p> : <div className="table-wrap"><table><thead><tr><th>Part Number</th><th>Drawing Number</th><th>Name</th><th>Category</th><th>Status</th><th>Updated At</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link href={`/parts/${item.id}`}>{item.partNumber}</Link></td><td>{item.drawingNumber ?? "—"}</td><td>{item.name}</td><td>{item.category.name}</td><td><span className={`badge ${item.status.toLowerCase()}`}>{item.status}</span></td><td>{formatInstantForBusinessDisplay(item.updatedAt)}</td></tr>)}</tbody></table></div>}<div className="pager"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>上一页</button><span>第 {page} 页 · {total} 条</span><button disabled={page * 25 >= total} onClick={() => setPage((value) => value + 1)}>下一页</button></div></section>;
}

export function NewPart() {
  const [categories, setCategories] = useState<Category[]>([]); const [categoryTotal, setCategoryTotal] = useState(0); const [categoryPage, setCategoryPage] = useState(1); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const loadCategories = useCallback(async (nextPage: number, append: boolean) => { try { const body = await json(await fetch(`/api/part-categories?status=ACTIVE&page=${nextPage}&pageSize=${CATEGORY_PAGE_SIZE}`)); setCategories((current) => append ? appendCategories(current, body.items) : body.items); setCategoryTotal(body.total); setCategoryPage(nextPage); } catch (cause) { setError(cause instanceof Error ? cause.message : "类别加载失败。"); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void loadCategories(1, false); }, 0); return () => window.clearTimeout(timer); }, [loadCategories]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); const data = new FormData(event.currentTarget); try { const body = await json(await fetch("/api/parts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(data)) })); setMessage(`已创建 ${body.partNumber}`); window.setTimeout(() => window.location.assign(`/parts/${body.id}`), 600); } catch (cause) { setError(cause instanceof Error ? cause.message : "创建失败。"); } }
  return <section className="panel narrow"><h1>新建零件</h1><p className="hint">Part Number 由系统自动生成。</p><form className="form-stack" onSubmit={submit}><label>类别<select name="categoryId" required><option value="">请选择 ACTIVE 类别</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>{canLoadMoreCategories(categoryTotal, categories.length) && <button type="button" onClick={() => void loadCategories(categoryPage + 1, true)}>加载更多类别</button>}<label>Drawing Number（可选）<input name="drawingNumber" /></label><label>名称<input name="name" required /></label><label>描述<textarea name="description" rows={4} /></label><button>创建</button>{message && <p role="status">{message}</p>}{error && <p className="error">{error}</p>}</form></section>;
}

export function PartDetail({ partId, canUpdate, canSetStatus }: { readonly partId: string; readonly canUpdate: boolean; readonly canSetStatus: boolean }) {
  const [part, setPart] = useState<Part | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [categories, setCategories] = useState<Category[]>([]); const [categoryTotal, setCategoryTotal] = useState(0); const [categoryPage, setCategoryPage] = useState(1);
  const load = useCallback(async () => { try { const body = await json(await fetch(`/api/parts/${partId}`)); setPart(body); } catch (cause) { setError(cause instanceof Error ? cause.message : "加载失败。"); } }, [partId]);
  const loadCategoryTargets = useCallback(async (nextPage: number, append: boolean) => { try { const body = await json(await fetch(`/api/part-categories?status=ACTIVE&page=${nextPage}&pageSize=${CATEGORY_PAGE_SIZE}`)); setCategories((current) => append ? appendCategories(current, body.items) : body.items); setCategoryTotal(body.total); setCategoryPage(nextPage); } catch { /* the current category remains available through PartMaster detail data */ } }, []);
  useEffect(() => { void load(); if (!canUpdate) return; const timer = window.setTimeout(() => { void loadCategoryTargets(1, false); }, 0); return () => window.clearTimeout(timer); }, [load, canUpdate, loadCategoryTargets]);
  async function act(method: string, body?: unknown) { setError(""); setMessage(""); try { const response = await fetch(`/api/parts/${partId}`, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); await json(response); setMessage("已保存。"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失败。"); } }
  async function status(status: string) { try { await json(await fetch(`/api/parts/${partId}/status`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) })); setMessage("状态已更新。"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失败。"); } }
  if (!part) return <section className="panel"><p>{error || "加载中…"}</p></section>;
  const selectorCategories = ensureCurrentCategory(categories, part.category);
  return <div className="split"><section className="panel"><h1>{part.partNumber}</h1><p className="hint">内部 ID：{part.id}</p><dl><dt>Drawing Number</dt><dd>{part.drawingNumber ?? "—"}</dd><dt>名称</dt><dd>{part.name}</dd><dt>类别</dt><dd>{part.category.name}（{part.category.status}）</dd><dt>状态</dt><dd><span className={`badge ${part.status.toLowerCase()}`}>{part.status}</span></dd><dt>描述</dt><dd>{part.description ?? "—"}</dd></dl>{canUpdate && <><h2>编辑</h2><form className="form-stack" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void act("PATCH", { categoryId: preserveCategoryId(part.category.id, data.get("categoryId")), drawingNumber: data.get("drawingNumber"), name: data.get("name"), description: data.get("description") }); }}><label>类别<select name="categoryId" defaultValue={part.category.id}>{selectorCategories.map((category) => <option key={category.id} value={category.id} disabled={category.status !== "ACTIVE"}>{category.name}{category.status !== "ACTIVE" ? "（停用）" : ""}</option>)}</select></label>{canLoadMoreCategories(categoryTotal, categories.length) && <button type="button" onClick={() => void loadCategoryTargets(categoryPage + 1, true)}>加载更多 ACTIVE 类别</button>}<label>Drawing Number<input name="drawingNumber" defaultValue={part.drawingNumber ?? ""} /></label><label>名称<input name="name" defaultValue={part.name} /></label><label>描述<textarea name="description" defaultValue={part.description ?? ""} rows={4} /></label><button>保存</button></form></>}{canSetStatus && <><h2>状态</h2><div className="button-row"><button disabled={part.status === "ACTIVE"} onClick={() => void status("ACTIVE")}>ACTIVE</button><button disabled={part.status === "INACTIVE"} onClick={() => void status("INACTIVE")}>INACTIVE</button></div></>}{message && <p role="status">{message}</p>}{error && <p className="error">{error}</p>}</section></div>;
}
