"use client";

import Link from "next/link";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { formatInstantForBusinessDisplay } from "@/platform/time";

type Revision = { id: string; revisionNo: number; status: string; changeSummary: string; part: { id: string; partNumber: string; drawingNumber: string | null; name: string }; createdBy: { id: string; displayName: string }; createdAt: string; updatedAt: string; lastSubmittedAt: string | null; releasedAt: string | null; releasedBy: { displayName: string } | null; };
type Review = { id: string; decision: string; reviewer: { displayName: string }; comment: string | null; creatorReviewOverride: boolean; overrideReason: string | null; decidedAt: string; };
type Page<T> = { items: T[]; page: number; pageSize: number; total: number };
async function json(response: Response) { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "请求失败。"); return body; }
const date = (value: string | null) => value ? formatInstantForBusinessDisplay(value) : "—";

export function RevisionsList({ partId, canCreate }: { readonly partId: string; readonly canCreate: boolean }) {
  const [result, setResult] = useState<Page<Revision>>({ items: [], page: 1, pageSize: 25, total: 0 }); const [error, setError] = useState("");
  const load = useCallback(async (requestedPage = 1, append = false) => { try { const response = await json(await fetch(`/api/parts/${partId}/revisions?page=${requestedPage}&pageSize=25`)) as Page<Revision>; setResult((current) => append ? { ...response, items: [...current.items, ...response.items] } : response); } catch (cause) { setError(cause instanceof Error ? cause.message : "加载失败。"); } }, [partId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  return <section className="panel"><div className="button-row"><h1>版本</h1>{canCreate && <Link href={`/parts/${partId}/revisions/new`}>新建版本</Link>}</div>{error && <p className="error">{error}</p>}<table><thead><tr><th>Revision No</th><th>Status</th><th>Change Summary</th><th>Creator</th><th>Created At</th><th>Last Submitted</th><th>Released At</th></tr></thead><tbody>{result.items.map((item) => <tr key={item.id}><td><Link href={`/parts/${partId}/revisions/${item.id}`}>{item.revisionNo}</Link></td><td>{item.status}</td><td>{item.changeSummary}</td><td>{item.createdBy.displayName}</td><td>{date(item.createdAt)}</td><td>{date(item.lastSubmittedAt)}</td><td>{date(item.releasedAt)}</td></tr>)}</tbody></table>{result.items.length === 0 && <p>暂无版本。</p>}{result.items.length < result.total && <button onClick={() => void load(result.page + 1, true)}>加载更多版本</button>}</section>;
}

export function NewRevision({ partId }: { readonly partId: string }) { const [error, setError] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); try { const data = new FormData(event.currentTarget); const revision = await json(await fetch(`/api/parts/${partId}/revisions`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ changeSummary: data.get("changeSummary") }) })); window.location.assign(`/parts/${partId}/revisions/${revision.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "创建失败。"); } } return <section className="panel narrow"><h1>新建版本</h1><form className="form-stack" onSubmit={submit}><label>Change Summary<textarea name="changeSummary" rows={6} required /></label><button>创建 DRAFT</button>{error && <p className="error">{error}</p>}</form></section>; }

export function RevisionDetail({ revisionId, parentPartId, actorId, canUpdate, canSubmit, canReturn, canApprove, canRelease, canCreatorReviewOverride }: { readonly revisionId: string; readonly parentPartId: string; readonly actorId: string; readonly canUpdate: boolean; readonly canSubmit: boolean; readonly canReturn: boolean; readonly canApprove: boolean; readonly canRelease: boolean; readonly canCreatorReviewOverride: boolean }) {
  const [revision, setRevision] = useState<Revision | null>(null); const [reviews, setReviews] = useState<Page<Review>>({ items: [], page: 1, pageSize: 25, total: 0 }); const [error, setError] = useState(""); const [overrideReason, setOverrideReason] = useState("");
  const load = useCallback(async (reviewPage = 1, append = false) => { try { const [current, history] = await Promise.all([json(await fetch(`/api/part-revisions/${revisionId}`)), json(await fetch(`/api/part-revisions/${revisionId}/reviews?page=${reviewPage}&pageSize=25`))]); setRevision(current); setReviews((existing) => append ? { ...history, items: [...existing.items, ...history.items] } : history); } catch (cause) { setError(cause instanceof Error ? cause.message : "加载失败。"); } }, [revisionId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function command(path: string, body?: Record<string, unknown>) { try { const options: RequestInit = { method: "POST" }; if (body !== undefined) { options.headers = { "content-type": "application/json" }; options.body = JSON.stringify(body); } await json(await fetch(`/api/part-revisions/${revisionId}/${path}`, options)); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失败。"); } }
  useEffect(() => { if (revision !== null && revision.part.id !== parentPartId) window.location.replace(`/parts/${parentPartId}/revisions`); }, [parentPartId, revision]);
  if (!revision) return <section className="panel"><p>{error || "加载中…"}</p></section>;
  if (revision.part.id !== parentPartId) return <section className="panel"><p>资源不存在。</p></section>;
  const editable = revision.status === "DRAFT" || revision.status === "RETURNED"; const creatorCollision = revision.createdBy.id === actorId;
  return <section className="panel"><h1>Revision {revision.revisionNo}</h1><p>{revision.part.partNumber} · {revision.part.name} · {revision.status}</p>{canUpdate && editable && <form className="form-stack" onSubmit={async (event) => { event.preventDefault(); try { const data = new FormData(event.currentTarget); await json(await fetch(`/api/part-revisions/${revisionId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ changeSummary: data.get("changeSummary") }) })); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存失败。"); } }}><label>Change Summary<textarea name="changeSummary" defaultValue={revision.changeSummary} rows={5} /></label><button>保存</button></form>}<p>{revision.changeSummary}</p><div className="button-row">{canSubmit && editable && <button onClick={() => void command("submit-review")}>提交审核</button>}{canReturn && !creatorCollision && revision.status === "REVIEWING" && <button onClick={() => { const comment = window.prompt("退回说明（必填）"); if (comment !== null) void command("return", { comment }); }}>退回</button>}{canApprove && !creatorCollision && revision.status === "REVIEWING" && <button onClick={() => { const comment = window.prompt("审核意见（可选）") ?? ""; void command("approve", { comment }); }}>批准</button>}{canRelease && revision.status === "APPROVED" && <button onClick={() => void command("release")}>发布</button>}</div>{creatorCollision && canCreatorReviewOverride && revision.status === "REVIEWING" && <form className="form-stack" onSubmit={(event) => { event.preventDefault(); const action = (new FormData(event.currentTarget).get("action") as string); const path = action === "RETURNED" ? "return" : "approve"; void command(path, { comment: new FormData(event.currentTarget).get("comment"), overrideCreatorReview: true, overrideReason }); }}><h2>紧急创建人审核越权</h2><p>仅在紧急情形下明确执行；系统会记录不可变 Review 和 Audit 原因。</p><label>决定<select name="action"><option value="APPROVED">批准</option><option value="RETURNED">退回</option></select></label><label>审核意见（退回时必填）<textarea name="comment" rows={3} /></label><label>越权原因（必填）<textarea value={overrideReason} onChange={(event) => setOverrideReason(event.target.value)} rows={3} required /></label><button>确认紧急越权</button></form>}<h2>审核历史</h2><ul>{reviews.items.map((review) => <li key={review.id}>{review.decision} · {review.reviewer.displayName} · {date(review.decidedAt)}{review.comment ? ` · ${review.comment}` : ""}{review.creatorReviewOverride ? ` · 紧急越权：${review.overrideReason}` : ""}</li>)}</ul>{reviews.items.length < reviews.total && <button onClick={() => void load(reviews.page + 1, true)}>加载更多审核历史</button>}{error && <p className="error">{error}</p>}</section>;
}
