import { beforeEach, describe, expect, it, vi } from "vitest";

import { AppError } from "@/platform/errors";

const mocks = vi.hoisted(() => ({
  identity: { validateSession: vi.fn() }, authorization: { requireAuthorization: vi.fn(), evaluateAuthorization: vi.fn() },
  revisions: { list: vi.fn(), get: vi.fn(), create: vi.fn(), update: vi.fn(), submit: vi.fn(), returnForReview: vi.fn(), approve: vi.fn(), release: vi.fn(), listReviews: vi.fn() },
}));
vi.mock("@/platform/identity-session", () => ({ createIdentitySessionService: () => mocks.identity }));
vi.mock("@/platform/authorization", async (original) => ({ ...(await original<typeof import("@/platform/authorization")>()), createAuthorizationService: () => mocks.authorization }));
vi.mock("@/modules/part-revision", async (original) => ({ ...(await original<typeof import("@/modules/part-revision")>()), createPartRevisionService: () => mocks.revisions }));

const account = { id: "11111111-1111-4111-8111-111111111111", organizationId: "22222222-2222-4222-8222-222222222222", primaryOrgUnitId: "33333333-3333-4333-8333-333333333333", username: "engineer", displayName: "Engineer", status: "ACTIVE", createdAt: new Date(), updatedAt: new Date() } as const;
const authenticated = { account, session: { id: "44444444-4444-4444-8444-444444444444", accountId: account.id, createdAt: new Date(), expiresAt: new Date(Date.now() + 1000), revokedAt: null, userAgent: "test" } } as const;
const denied = () => new AppError({ code: "AUTH.PERMISSION_DENIED", httpStatus: 403, internalMessage: "PERMISSION_DENIED", publicMessage: "无权执行此操作。" });
const missing = () => new AppError({ code: "RESOURCE.NOT_FOUND", httpStatus: 404, internalMessage: "PART_REVISION_NOT_FOUND", publicMessage: "资源不存在。" });
const revision = { id: account.id, revisionNo: 1, status: "DRAFT", changeSummary: "summary", part: { id: account.id, partNumber: "PART-000001", drawingNumber: null, name: "Part" }, createdBy: account, createdAt: new Date(), updatedAt: new Date(), lastSubmittedAt: null, releasedBy: null, releasedAt: null };
function request(path: string, method: "GET" | "POST" | "PATCH", body?: unknown) { return new Request(`http://localhost${path}`, { method, headers: { cookie: "plm_session=opaque-token", ...(body === undefined ? {} : { "content-type": "application/json" }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); }
const params = { params: Promise.resolve({ revisionId: account.id }) };

describe("Slice 2B API contracts", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.identity.validateSession.mockResolvedValue(authenticated); mocks.authorization.requireAuthorization.mockResolvedValue(undefined); mocks.revisions.list.mockResolvedValue({ items: [], page: 1, pageSize: 25, total: 0 }); mocks.revisions.listReviews.mockResolvedValue({ items: [], page: 1, pageSize: 25, total: 0 }); mocks.revisions.get.mockResolvedValue(revision); mocks.revisions.create.mockResolvedValue(revision); mocks.revisions.update.mockResolvedValue(revision); mocks.revisions.submit.mockResolvedValue(revision); mocks.revisions.returnForReview.mockResolvedValue(revision); mocks.revisions.approve.mockResolvedValue(revision); mocks.revisions.release.mockResolvedValue(revision); });
  it("returns 401 without an authenticated session and leaves mutations untouched", async () => { mocks.identity.validateSession.mockRejectedValue(new AppError({ code: "AUTH.AUTHENTICATION_REQUIRED", httpStatus: 401, internalMessage: "AUTHENTICATION_REQUIRED", publicMessage: "需要认证。" })); const { POST } = await import("./part-revisions/[revisionId]/approve/route"); expect((await POST(request(`/api/part-revisions/${account.id}/approve`, "POST", { comment: "ok" }), params)).status).toBe(401); expect(mocks.revisions.approve).not.toHaveBeenCalled(); });
  it("enforces role authorization for authoring and release endpoints", async () => { mocks.authorization.requireAuthorization.mockRejectedValueOnce(denied()); const { POST: create } = await import("./parts/[partId]/revisions/route"); expect((await create(request(`/api/parts/${account.id}/revisions`, "POST", { changeSummary: "new" }), { params: Promise.resolve({ partId: account.id }) })).status).toBe(403); mocks.authorization.requireAuthorization.mockRejectedValueOnce(denied()); const { POST: release } = await import("./part-revisions/[revisionId]/release/route"); expect((await release(request(`/api/part-revisions/${account.id}/release`, "POST"), params)).status).toBe(403); });
  it("accepts bodyless submit and release commands, and permits only an empty object when supplied", async () => { const { POST: submit } = await import("./part-revisions/[revisionId]/submit-review/route"); const { POST: release } = await import("./part-revisions/[revisionId]/release/route"); expect((await submit(request(`/api/part-revisions/${account.id}/submit-review`, "POST"), params)).status).toBe(200); expect((await release(request(`/api/part-revisions/${account.id}/release`, "POST", {}), params)).status).toBe(200); expect((await submit(request(`/api/part-revisions/${account.id}/submit-review`, "POST", { status: "REVIEWING" }), params)).status).toBe(400); });
  it("rejects protected fields and non-boolean creator-review override input", async () => { const { POST: create } = await import("./parts/[partId]/revisions/route"); expect((await create(request(`/api/parts/${account.id}/revisions`, "POST", { changeSummary: "new", organizationId: account.organizationId }), { params: Promise.resolve({ partId: account.id }) })).status).toBe(400); const { POST: approve } = await import("./part-revisions/[revisionId]/approve/route"); mocks.revisions.approve.mockRejectedValue(new AppError({ code: "PLATFORM.VALIDATION_FAILED", httpStatus: 400, internalMessage: "INVALID_PART_REVISION_INPUT", publicMessage: "请求参数无效。" })); expect((await approve(request(`/api/part-revisions/${account.id}/approve`, "POST", { overrideCreatorReview: "true" }), params)).status).toBe(400); });
  it("maps malformed and cross-organization nested resources to 404 rather than an empty success", async () => { mocks.revisions.list.mockRejectedValue(missing()); mocks.revisions.get.mockRejectedValue(missing()); mocks.revisions.listReviews.mockRejectedValue(missing()); const { GET: list } = await import("./parts/[partId]/revisions/route"); const { GET: get } = await import("./part-revisions/[revisionId]/route"); const { GET: reviews } = await import("./part-revisions/[revisionId]/reviews/route"); expect((await list(request("/api/parts/not-a-uuid/revisions", "GET"), { params: Promise.resolve({ partId: "not-a-uuid" }) })).status).toBe(404); expect((await get(request("/api/part-revisions/not-a-uuid", "GET"), { params: Promise.resolve({ revisionId: "not-a-uuid" }) })).status).toBe(404); expect((await reviews(request("/api/part-revisions/not-a-uuid/reviews", "GET"), { params: Promise.resolve({ revisionId: "not-a-uuid" }) })).status).toBe(404); });
  it("has no DELETE surface and forwards explicit override fields only to the decision use case", async () => { const route = await import("./part-revisions/[revisionId]/route"); expect((route as { DELETE?: unknown }).DELETE).toBeUndefined(); const { POST } = await import("./part-revisions/[revisionId]/return/route"); expect((await POST(request(`/api/part-revisions/${account.id}/return`, "POST", { comment: "reason", overrideCreatorReview: true, overrideReason: "emergency" }), params)).status).toBe(200); expect(mocks.revisions.returnForReview).toHaveBeenCalledWith(expect.objectContaining({ overrideCreatorReview: true, overrideReason: "emergency" })); });
});
