import { randomUUID } from "node:crypto";
import { Prisma, type PrismaClient } from "@prisma/client";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { createTestPrismaClient } from "@/platform/database/prisma-client";
import { createNumberingServiceForPrisma } from "@/platform/numbering/application/numbering-service";
import { createAuthenticatedActor, createRequestContext } from "@/platform/request-context";
import { createEquipmentServiceForPrisma } from "./infrastructure/equipment-prisma";

const prisma = createTestPrismaClient(); const organizations: string[] = []; const options = { maxWait: 10_000, timeout: 60_000 };
const defer = () => { let resolve!: () => void; return { promise: new Promise<void>((done) => { resolve = done; }), resolve }; };
const context = (account: { id: string; organizationId: string; primaryOrgUnitId: string }) => createRequestContext({ actor: createAuthenticatedActor({ kind: "user", userId: account.id, sessionId: randomUUID(), organizationId: account.organizationId, organizationUnitId: account.primaryOrgUnitId }) });
const service = (client: PrismaClient = prisma) => createEquipmentServiceForPrisma(client, createNumberingServiceForPrisma(client));
async function fixture() { const suffix = randomUUID().slice(0, 8).toUpperCase(); const organization = await prisma.organization.create({ data: { code: `EQ-${suffix}`, name: "Equipment test" } }); organizations.push(organization.id); const root = await prisma.orgUnit.create({ data: { organizationId: organization.id, code: "ROOT", name: "Root", sortOrder: 0 } }); const account = await prisma.account.create({ data: { organizationId: organization.id, primaryOrgUnitId: root.id, username: `eq-${suffix.toLowerCase()}`, normalizedUsername: `eq-${suffix.toLowerCase()}`, displayName: "Engineer", passwordHash: "test", status: "ACTIVE" } }); return { organization, root, account, context: context(account), equipment: service() }; }
async function waitFor(condition: () => Promise<boolean>) { const deadline = Date.now() + 15_000; while (!(await condition())) { if (Date.now() > deadline) throw new Error("Timed out waiting for PostgreSQL lock evidence"); await new Promise<void>((done) => setImmediate(done)); } }
async function gate(table: "equipment" | "equipment_position", id: string) { const client = createTestPrismaClient(); const held = defer(); const release = defer(); let pid = 0; const promise = client.$transaction(async (tx) => { pid = (await tx.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`)[0]!.pid; await tx.$queryRaw(Prisma.sql`SELECT id FROM ${Prisma.raw(table)} WHERE id = ${id}::uuid FOR UPDATE`); held.resolve(); await release.promise; }, options); await held.promise; return { client, pid, release, promise }; }
async function blocker(pid: number, gatePid: number) { await waitFor(async () => { const activity = await prisma.$queryRaw<Array<{ blocked: number[] }>>`SELECT pg_blocking_pids(pid) AS blocked FROM pg_stat_activity WHERE pid = ${pid}`; const locks = await prisma.$queryRaw<Array<{ count: number }>>`SELECT count(*)::integer AS count FROM pg_locks WHERE pid = ${pid} AND NOT granted`; return activity.some((row) => row.blocked.includes(gatePid)) && (locks[0]?.count ?? 0) > 0; }); }
function observed(client: PrismaClient, pids: number[]) { const transaction = client.$transaction.bind(client); return new Proxy(client, { get(target, property, receiver) { if (property !== "$transaction") return Reflect.get(target, property, receiver); return async (callback: (tx: never) => Promise<unknown>) => transaction(async (tx) => { pids.push((await tx.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`)[0]!.pid); return callback(tx as never); }, options); } }) as PrismaClient; }
async function chain(pids: readonly number[], gatePid: number) { await waitFor(async () => { if (pids.length !== 2) return false; const rows = await prisma.$queryRaw<Array<{ count: number }>>`WITH RECURSIVE chain AS (SELECT a.pid AS waiter_pid, unnest(pg_blocking_pids(a.pid)) AS blocker_pid, ARRAY[a.pid]::integer[] AS visited FROM pg_stat_activity a WHERE a.wait_event_type = 'Lock' AND a.pid IN (${pids[0]}, ${pids[1]}) UNION ALL SELECT c.waiter_pid, unnest(pg_blocking_pids(c.blocker_pid)), c.visited || c.blocker_pid FROM chain c WHERE NOT c.blocker_pid = ANY(c.visited)) SELECT count(DISTINCT waiter_pid)::integer AS count FROM chain WHERE blocker_pid = ${gatePid}`; const locks = await prisma.$queryRaw<Array<{ count: number }>>`SELECT count(*)::integer AS count FROM pg_locks WHERE pid IN (${pids[0]}, ${pids[1]}) AND NOT granted`; return rows[0]?.count === 2 && (locks[0]?.count ?? 0) === 2; }); }
async function numberingWaiters(gatePid: number) { let pids: number[] = []; await waitFor(async () => { const activity = await prisma.$queryRaw<Array<{ pid: number }>>`SELECT pid FROM pg_stat_activity WHERE wait_event_type = 'Lock' AND query ILIKE '%INSERT INTO "numbering_sequence"%'`; pids = activity.map((row) => row.pid); if (pids.length !== 2) return false; const chainRows = await prisma.$queryRaw<Array<{ count: number }>>`WITH RECURSIVE chain AS (SELECT a.pid AS waiter_pid, unnest(pg_blocking_pids(a.pid)) AS blocker_pid, ARRAY[a.pid]::integer[] AS visited FROM pg_stat_activity a WHERE a.pid IN (${pids[0]}, ${pids[1]}) UNION ALL SELECT c.waiter_pid, unnest(pg_blocking_pids(c.blocker_pid)), c.visited || c.blocker_pid FROM chain c WHERE NOT c.blocker_pid = ANY(c.visited)) SELECT count(DISTINCT waiter_pid)::integer AS count FROM chain WHERE blocker_pid = ${gatePid}`; const locks = await prisma.$queryRaw<Array<{ count: number }>>`SELECT count(DISTINCT pid)::integer AS count FROM pg_locks WHERE pid IN (${pids[0]}, ${pids[1]}) AND NOT granted`; return chainRows[0]?.count === 2 && locks[0]?.count === 2; }); return pids; }
const inactive = { code: "BUSINESS_RULE.VIOLATION", internalMessage: "EQUIPMENT_INACTIVE" };
async function removeAuditFailureTrigger() { await prisma.$executeRaw`DROP TRIGGER IF EXISTS codex_equipment_fail_audit_trigger ON audit_log`; await prisma.$executeRaw`DROP FUNCTION IF EXISTS codex_equipment_fail_audit()`; }
async function installAuditFailureTrigger() { await removeAuditFailureTrigger(); await prisma.$executeRaw(Prisma.sql`CREATE FUNCTION codex_equipment_fail_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."requestId" LIKE 'equip-audit-fail-%' THEN RAISE EXCEPTION 'equip-audit-fail'; END IF; RETURN NEW; END; $$`); await prisma.$executeRaw(Prisma.sql`CREATE TRIGGER codex_equipment_fail_audit_trigger BEFORE INSERT ON audit_log FOR EACH ROW EXECUTE FUNCTION codex_equipment_fail_audit()`); }
function pauseAfterFirstLockedRow(client: PrismaClient) { const locked = defer(); const release = defer(); let pid = 0; const transaction = client.$transaction.bind(client); const paused = new Proxy(client, { get(target, property, receiver) { if (property !== "$transaction") return Reflect.get(target, property, receiver); return async (callback: (tx: never) => Promise<unknown>) => transaction(async (tx) => { let pausedOnce = false; const transactionClient = new Proxy(tx, { get(inner, key, innerReceiver) { if (key !== "$queryRaw") return Reflect.get(inner, key, innerReceiver); const queryRaw = inner.$queryRaw as (query: TemplateStringsArray | Prisma.Sql, ...values: unknown[]) => Promise<unknown>; return async (query: TemplateStringsArray | Prisma.Sql, ...values: unknown[]) => { const result = await queryRaw.call(inner, query, ...values); if (!pausedOnce) { pausedOnce = true; pid = (await inner.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`)[0]!.pid; locked.resolve(); await release.promise; } return result; }; } }); return callback(transactionClient as never); }, options); } }) as PrismaClient; return { client: paused, locked, release, get pid() { return pid; } }; }
function pauseAfterPositionUpdate(client: PrismaClient) { const updated = defer(); const release = defer(); let pid = 0; const transaction = client.$transaction.bind(client); const paused = new Proxy(client, { get(target, property, receiver) { if (property !== "$transaction") return Reflect.get(target, property, receiver); return async (callback: (tx: never) => Promise<unknown>) => transaction(async (tx) => { const transactionClient = new Proxy(tx, { get(inner, key, innerReceiver) { if (key !== "equipmentPosition") return Reflect.get(inner, key, innerReceiver); return new Proxy(inner.equipmentPosition, { get(delegate, method, delegateReceiver) { if (method !== "update") return Reflect.get(delegate, method, delegateReceiver); return async (...args: never[]) => { const result = await (delegate.update as (...values: never[]) => Promise<unknown>)(...args); pid = (await inner.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`)[0]!.pid; updated.resolve(); await release.promise; return result; }; } }); } }); return callback(transactionClient as never); }, options); } }) as PrismaClient; return { client: paused, updated, release, get pid() { return pid; } }; }
afterEach(async () => { await removeAuditFailureTrigger(); const ids = organizations.splice(0); if (!ids.length) return; await prisma.equipmentPosition.deleteMany({ where: { organizationId: { in: ids } } }); await prisma.equipment.deleteMany({ where: { organizationId: { in: ids } } }); await prisma.auditLog.deleteMany({ where: { organizationId: { in: ids } } }); await prisma.numberingSequence.deleteMany({ where: { organizationId: { in: ids } } }); await prisma.account.deleteMany({ where: { organizationId: { in: ids } } }); await prisma.orgUnit.deleteMany({ where: { organizationId: { in: ids } } }); await prisma.organization.deleteMany({ where: { id: { in: ids } } }); }); afterAll(async () => { await removeAuditFailureTrigger(); await prisma.$disconnect(); });
describe("Slice 2C PostgreSQL acceptance", () => {
  it("EQUIP-DB-01 Equipment belongs to Organization and equipmentNumber is unique within it", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); await expect(prisma.equipment.create({ data: { organizationId: s.organization.id, equipmentNumber: e.equipmentNumber, name: "duplicate" } })).rejects.toMatchObject({ code: "P2002" }); });
  it("EQUIP-DB-02 different Organizations may both own EQ-000001", async () => { const a = await fixture(); const b = await fixture(); await expect(a.equipment.createEquipment({ context: a.context, name: "A" })).resolves.toMatchObject({ equipmentNumber: "EQ-000001" }); await expect(b.equipment.createEquipment({ context: b.context, name: "B" })).resolves.toMatchObject({ equipmentNumber: "EQ-000001" }); });
  it("EQUIP-DB-03 EquipmentPosition composite Organization FK rejects cross-Organization relation", async () => { const a = await fixture(); const b = await fixture(); const e = await b.equipment.createEquipment({ context: b.context, name: "B" }); await expect(prisma.equipmentPosition.create({ data: { organizationId: a.organization.id, equipmentId: e.id, positionCode: "P", normalizedPositionCode: "P", name: "cross" } })).rejects.toMatchObject({ code: "P2003" }); });
  it("EQUIP-DB-04 normalized positionCode is unique within one Equipment", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: " top ", name: "Top" }); await expect(s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "TOP", name: "Again" })).rejects.toMatchObject({ internalMessage: "EQUIPMENT_POSITION_CODE_CONFLICT" }); });
  it("EQUIP-DB-05 same normalized positionCode is allowed on different Equipment", async () => { const s = await fixture(); const [a, b] = await Promise.all([s.equipment.createEquipment({ context: s.context, name: "A" }), s.equipment.createEquipment({ context: s.context, name: "B" })]); await expect(Promise.all([s.equipment.createPosition({ context: s.context, equipmentId: a.id, positionCode: "TOP", name: "A" }), s.equipment.createPosition({ context: s.context, equipmentId: b.id, positionCode: "top", name: "B" })])).resolves.toHaveLength(2); });
  it("EQUIP-DB-06 concurrent Equipment creates use separate connections and receive distinct monotonic numbers", async () => { const s = await fixture(); await service().createEquipment({ context: s.context, name: "seed" }); const gateClient = createTestPrismaClient(); const held = defer(); const release = defer(); let gatePid = 0; const lock = gateClient.$transaction(async (tx) => { gatePid = (await tx.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`)[0]!.pid; await tx.$queryRaw`SELECT id FROM numbering_sequence WHERE "organizationId" = ${s.organization.id}::uuid AND key = 'equipment' FOR UPDATE`; held.resolve(); await release.promise; }, options); await held.promise; const a = createTestPrismaClient(); const b = createTestPrismaClient(); const writers = [service(a).createEquipment({ context: s.context, name: "A" }), service(b).createEquipment({ context: s.context, name: "B" })]; try { const pids = await numberingWaiters(gatePid); expect(new Set(pids).size).toBe(2); release.resolve(); const rows = await Promise.all(writers); expect(rows.map((row) => row.equipmentNumber).sort()).toEqual(["EQ-000002", "EQ-000003"]); } finally { release.resolve(); await Promise.allSettled([...writers, lock]); await Promise.all([gateClient.$disconnect(), a.$disconnect(), b.$disconnect()]); } }, 90_000);
  it("EQUIP-DB-07 failed Equipment create consumes allocated number and never reuses it", async () => { const s = await fixture(); const requestId = "equip-audit-fail-number"; await installAuditFailureTrigger(); try { await expect(s.equipment.createEquipment({ context: { ...s.context, requestId: requestId as never }, name: "fails after allocation" })).rejects.toThrow("equip-audit-fail"); } finally { await removeAuditFailureTrigger(); } expect(await prisma.equipment.count({ where: { organizationId: s.organization.id } })).toBe(0); expect(await prisma.auditLog.count({ where: { organizationId: s.organization.id, requestId } })).toBe(0); await expect(prisma.numberingSequence.findUnique({ where: { organizationId_key: { organizationId: s.organization.id, key: "equipment" } } })).resolves.toMatchObject({ currentValue: BigInt(1) }); await expect(s.equipment.createEquipment({ context: s.context, name: "after" })).resolves.toMatchObject({ equipmentNumber: "EQ-000002" }); });
  it("EQUIP-DB-08 Equipment create and Audit are atomic after Numbering allocation", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); await expect(prisma.auditLog.findFirst({ where: { targetId: e.id, action: "equipment.create" } })).resolves.toBeTruthy(); });
  it("EQUIP-DB-09 Equipment update/status and Audit are atomic and no-op creates no Audit", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const before = await prisma.auditLog.count({ where: { targetId: e.id } }); await s.equipment.updateEquipment({ context: s.context, equipmentId: e.id, name: "A" }); await s.equipment.setEquipmentStatus({ context: s.context, equipmentId: e.id, status: "ACTIVE" }); expect(await prisma.auditLog.count({ where: { targetId: e.id } })).toBe(before); });
  it("EQUIP-DB-10 Position create requires ACTIVE Equipment and Position plus Audit commit atomically", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "Position" }); await expect(prisma.auditLog.findFirst({ where: { targetId: p.id, action: "equipment_position.create" } })).resolves.toBeTruthy(); });
  it("EQUIP-DB-11 INACTIVE Equipment rejects new Position creation", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); await s.equipment.setEquipmentStatus({ context: s.context, equipmentId: e.id, status: "INACTIVE" }); await expect(s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" })).rejects.toMatchObject(inactive); });
  it("EQUIP-DB-12 Equipment deactivate versus Position create serializes on Equipment with no stale ACTIVE decision", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const deactivator = createTestPrismaClient(); const creator = createTestPrismaClient(); const paused = pauseAfterFirstLockedRow(deactivator); const pids: number[] = []; let deactivate: Promise<unknown> | undefined; let create: Promise<unknown> | undefined; try { deactivate = service(paused.client).setEquipmentStatus({ context: s.context, equipmentId: e.id, status: "INACTIVE" }); await paused.locked.promise; create = service(observed(creator, pids)).createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); await waitFor(async () => pids.length === 1); await blocker(pids[0]!, paused.pid); paused.release.resolve(); await expect(deactivate).resolves.toMatchObject({ status: "INACTIVE" }); await expect(create).rejects.toMatchObject(inactive); expect(await prisma.equipmentPosition.count({ where: { equipmentId: e.id } })).toBe(0); } finally { paused.release.resolve(); await Promise.allSettled([deactivate, create].filter((writer): writer is Promise<unknown> => writer !== undefined)); await Promise.all([deactivator.$disconnect(), creator.$disconnect()]); } }, 90_000);
  it("EQUIP-DB-13 Position reactivation requires ACTIVE Equipment", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); await s.equipment.setPositionStatus({ context: s.context, positionId: p.id, status: "INACTIVE" }); await s.equipment.setEquipmentStatus({ context: s.context, equipmentId: e.id, status: "INACTIVE" }); await expect(s.equipment.setPositionStatus({ context: s.context, positionId: p.id, status: "ACTIVE" })).rejects.toMatchObject(inactive); });
  it("EQUIP-DB-14 Equipment deactivate versus Position reactivate uses Equipment then Position locks with no stale ACTIVE decision", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); await s.equipment.setPositionStatus({ context: s.context, positionId: p.id, status: "INACTIVE" }); const deactivator = createTestPrismaClient(); const reactivator = createTestPrismaClient(); const paused = pauseAfterFirstLockedRow(deactivator); const pids: number[] = []; let deactivate: Promise<unknown> | undefined; let reactivate: Promise<unknown> | undefined; try { deactivate = service(paused.client).setEquipmentStatus({ context: s.context, equipmentId: e.id, status: "INACTIVE" }); await paused.locked.promise; reactivate = service(observed(reactivator, pids)).setPositionStatus({ context: s.context, positionId: p.id, status: "ACTIVE" }); await waitFor(async () => pids.length === 1); await blocker(pids[0]!, paused.pid); paused.release.resolve(); await expect(deactivate).resolves.toMatchObject({ status: "INACTIVE" }); await expect(reactivate).rejects.toMatchObject(inactive); await expect(prisma.equipmentPosition.findUnique({ where: { id: p.id } })).resolves.toMatchObject({ status: "INACTIVE" }); } finally { paused.release.resolve(); await Promise.allSettled([deactivate, reactivate].filter((writer): writer is Promise<unknown> => writer !== undefined)); await Promise.all([deactivator.$disconnect(), reactivator.$disconnect()]); } }, 90_000);
  it("EQUIP-DB-15 Equipment deactivation does not cascade Position status", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); await s.equipment.setEquipmentStatus({ context: s.context, equipmentId: e.id, status: "INACTIVE" }); await expect(prisma.equipmentPosition.findUnique({ where: { id: p.id } })).resolves.toMatchObject({ status: "ACTIVE" }); });
  it("EQUIP-DB-16 same normalized Position code race has exact STATE.CONFLICT EQUIPMENT_POSITION_CODE_CONFLICT loser", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const a = createTestPrismaClient(); const b = createTestPrismaClient(); const pids: number[] = []; const held = await gate("equipment", e.id); let creates: Promise<unknown>[] = []; try { creates = [service(observed(a, pids)).createPosition({ context: s.context, equipmentId: e.id, positionCode: "TOP", name: "A" }), service(observed(b, pids)).createPosition({ context: s.context, equipmentId: e.id, positionCode: " top ", name: "B" })]; await chain(pids, held.pid); held.release.resolve(); const settled = await Promise.allSettled(creates); expect(settled.filter((result) => result.status === "fulfilled")).toHaveLength(1); expect(settled.find((result) => result.status === "rejected")).toMatchObject({ reason: { code: "STATE.CONFLICT", internalMessage: "EQUIPMENT_POSITION_CODE_CONFLICT" } }); } finally { held.release.resolve(); await Promise.allSettled([...creates, held.promise]); await Promise.all([held.client.$disconnect(), a.$disconnect(), b.$disconnect()]); }
    const first = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P-A", name: "A" }); const second = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P-B", name: "B" }); const updater = createTestPrismaClient(); const competitor = createTestPrismaClient(); const paused = pauseAfterPositionUpdate(updater); const renamePids: number[] = []; let rename: Promise<unknown> | undefined; let competingRename: Promise<unknown> | undefined; try { rename = service(paused.client).updatePosition({ context: s.context, positionId: first.id, positionCode: "SLOT-X" }); await paused.updated.promise; competingRename = service(observed(competitor, renamePids)).updatePosition({ context: s.context, positionId: second.id, positionCode: " slot-x " }); await waitFor(async () => renamePids.length === 1); await blocker(renamePids[0]!, paused.pid); paused.release.resolve(); await expect(rename).resolves.toMatchObject({ positionCode: "SLOT-X" }); await expect(competingRename).rejects.toMatchObject({ code: "STATE.CONFLICT", internalMessage: "EQUIPMENT_POSITION_CODE_CONFLICT" }); expect(await prisma.equipmentPosition.count({ where: { equipmentId: e.id, normalizedPositionCode: "SLOT-X" } })).toBe(1); } finally { paused.release.resolve(); await Promise.allSettled([rename, competingRename].filter((writer): writer is Promise<unknown> => writer !== undefined)); await Promise.all([updater.$disconnect(), competitor.$disconnect()]); } }, 90_000);
  it("EQUIP-DB-17 Position update/status and Audit are atomic and no-op creates no Audit", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); const before = await prisma.auditLog.count({ where: { targetId: p.id } }); await s.equipment.updatePosition({ context: s.context, positionId: p.id, name: "P" }); await s.equipment.setPositionStatus({ context: s.context, positionId: p.id, status: "ACTIVE" }); expect(await prisma.auditLog.count({ where: { targetId: p.id } })).toBe(before); });
  it("EQUIP-DB-18 Equipment services expose no hard delete and RESTRICT preserves relations", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); expect("deleteEquipment" in s.equipment).toBe(false); expect("deletePosition" in s.equipment).toBe(false); await expect(prisma.equipment.delete({ where: { id: e.id } })).rejects.toMatchObject({ code: "P2003" }); });
});

describe("Slice 2C Audit forced-failure rollback", () => {
  const failing = (base: ReturnType<typeof context>, action: string) => ({ ...base, requestId: `equip-audit-fail-${action}` as never });
  it("EQUIP-AUDIT-CREATE rolls back the Equipment row and Audit row", async () => { const s = await fixture(); const request = failing(s.context, "equipment-create"); await installAuditFailureTrigger(); try { await expect(s.equipment.createEquipment({ context: request, name: "fail" })).rejects.toThrow("equip-audit-fail"); } finally { await removeAuditFailureTrigger(); } expect(await prisma.equipment.count({ where: { organizationId: s.organization.id } })).toBe(0); expect(await prisma.auditLog.count({ where: { requestId: request.requestId } })).toBe(0); });
  it("EQUIP-AUDIT-UPDATE rolls back the Equipment mutation and Audit row", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "before" }); const request = failing(s.context, "equipment-update"); await installAuditFailureTrigger(); try { await expect(s.equipment.updateEquipment({ context: request, equipmentId: e.id, name: "after" })).rejects.toThrow("equip-audit-fail"); } finally { await removeAuditFailureTrigger(); } await expect(prisma.equipment.findUnique({ where: { id: e.id } })).resolves.toMatchObject({ name: "before" }); expect(await prisma.auditLog.count({ where: { requestId: request.requestId } })).toBe(0); });
  it("EQUIP-AUDIT-STATUS rolls back Equipment status and Audit row", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const request = failing(s.context, "equipment-status"); await installAuditFailureTrigger(); try { await expect(s.equipment.setEquipmentStatus({ context: request, equipmentId: e.id, status: "INACTIVE" })).rejects.toThrow("equip-audit-fail"); } finally { await removeAuditFailureTrigger(); } await expect(prisma.equipment.findUnique({ where: { id: e.id } })).resolves.toMatchObject({ status: "ACTIVE" }); expect(await prisma.auditLog.count({ where: { requestId: request.requestId } })).toBe(0); });
  it("POSITION-AUDIT-CREATE rolls back the Position row and Audit row", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const request = failing(s.context, "position-create"); await installAuditFailureTrigger(); try { await expect(s.equipment.createPosition({ context: request, equipmentId: e.id, positionCode: "P", name: "P" })).rejects.toThrow("equip-audit-fail"); } finally { await removeAuditFailureTrigger(); } expect(await prisma.equipmentPosition.count({ where: { equipmentId: e.id } })).toBe(0); expect(await prisma.auditLog.count({ where: { requestId: request.requestId } })).toBe(0); });
  it("POSITION-AUDIT-UPDATE rolls back the Position mutation and Audit row", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "before" }); const request = failing(s.context, "position-update"); await installAuditFailureTrigger(); try { await expect(s.equipment.updatePosition({ context: request, positionId: p.id, name: "after" })).rejects.toThrow("equip-audit-fail"); } finally { await removeAuditFailureTrigger(); } await expect(prisma.equipmentPosition.findUnique({ where: { id: p.id } })).resolves.toMatchObject({ name: "before" }); expect(await prisma.auditLog.count({ where: { requestId: request.requestId } })).toBe(0); });
  it("POSITION-AUDIT-STATUS rolls back Position status and Audit row", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); const request = failing(s.context, "position-status"); await installAuditFailureTrigger(); try { await expect(s.equipment.setPositionStatus({ context: request, positionId: p.id, status: "INACTIVE" })).rejects.toThrow("equip-audit-fail"); } finally { await removeAuditFailureTrigger(); } await expect(prisma.equipmentPosition.findUnique({ where: { id: p.id } })).resolves.toMatchObject({ status: "ACTIVE" }); expect(await prisma.auditLog.count({ where: { requestId: request.requestId } })).toBe(0); });
  it("POSITION-AUDIT-NOOP does not invoke Audit and remains successful", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); const request = failing(s.context, "position-noop"); await installAuditFailureTrigger(); try { await expect(s.equipment.updatePosition({ context: request, positionId: p.id, name: "P" })).resolves.toMatchObject({ id: p.id }); await expect(s.equipment.setPositionStatus({ context: request, positionId: p.id, status: "ACTIVE" })).resolves.toMatchObject({ id: p.id }); } finally { await removeAuditFailureTrigger(); } expect(await prisma.auditLog.count({ where: { requestId: request.requestId } })).toBe(0); });
});

describe("Slice 2C successful Audit acceptance", () => {
  it("EQUIP-AUDIT-CREATE-SUCCESS records exact Equipment create details", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const event = await prisma.auditLog.findFirstOrThrow({ where: { targetId: e.id, action: "equipment.create" }, orderBy: { occurredAt: "desc" } }); expect(event.details).toEqual({ equipmentNumber: e.equipmentNumber, status: "ACTIVE" }); });
  it("POSITION-AUDIT-CREATE-SUCCESS records exact Position create details", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); const event = await prisma.auditLog.findFirstOrThrow({ where: { targetId: p.id, action: "equipment_position.create" }, orderBy: { occurredAt: "desc" } }); expect(event.details).toEqual({ equipmentId: e.id, positionCode: "P", status: "ACTIVE" }); });
  it("EQUIP-AUDIT-UPDATE-SUCCESS records only changed Equipment metadata", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "before" }); await s.equipment.updateEquipment({ context: s.context, equipmentId: e.id, name: "after" }); const event = await prisma.auditLog.findFirstOrThrow({ where: { targetId: e.id, action: "equipment.update" }, orderBy: { occurredAt: "desc" } }); expect(event.details).toEqual({ changed: { name: "after" } }); });
  it("EQUIP-AUDIT-STATUS-SUCCESS records Equipment status transition", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); await s.equipment.setEquipmentStatus({ context: s.context, equipmentId: e.id, status: "INACTIVE" }); const event = await prisma.auditLog.findFirstOrThrow({ where: { targetId: e.id, action: "equipment.set_status" }, orderBy: { occurredAt: "desc" } }); expect(event.details).toEqual({ fromStatus: "ACTIVE", toStatus: "INACTIVE" }); });
  it("POSITION-AUDIT-UPDATE-SUCCESS records only changed Position metadata and parent Equipment", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "before" }); await s.equipment.updatePosition({ context: s.context, positionId: p.id, positionCode: "Q", name: "after" }); const event = await prisma.auditLog.findFirstOrThrow({ where: { targetId: p.id, action: "equipment_position.update" }, orderBy: { occurredAt: "desc" } }); expect(event.details).toEqual({ equipmentId: e.id, changed: { positionCode: "Q", name: "after" } }); });
  it("POSITION-AUDIT-STATUS-SUCCESS records Position status transition and parent Equipment", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: "P", name: "P" }); await s.equipment.setPositionStatus({ context: s.context, positionId: p.id, status: "INACTIVE" }); const event = await prisma.auditLog.findFirstOrThrow({ where: { targetId: p.id, action: "equipment_position.set_status" }, orderBy: { occurredAt: "desc" } }); expect(event.details).toEqual({ equipmentId: e.id, fromStatus: "ACTIVE", toStatus: "INACTIVE" }); });
});

describe("Slice 2C cross-Organization service IDOR", () => {
  const notFound = { code: "RESOURCE.NOT_FOUND", httpStatus: 404 };
  it("EQUIP-IDOR-01 treats a foreign Equipment UUID as not found for all Equipment and nested Position operations", async () => { const a = await fixture(); const b = await fixture(); const foreign = await b.equipment.createEquipment({ context: b.context, name: "foreign" }); for (const operation of [() => a.equipment.getEquipment({ context: a.context, equipmentId: foreign.id }), () => a.equipment.updateEquipment({ context: a.context, equipmentId: foreign.id, name: "no" }), () => a.equipment.setEquipmentStatus({ context: a.context, equipmentId: foreign.id, status: "INACTIVE" }), () => a.equipment.listPositions({ context: a.context, equipmentId: foreign.id }), () => a.equipment.createPosition({ context: a.context, equipmentId: foreign.id, positionCode: "P", name: "no" })]) await expect(operation()).rejects.toMatchObject(notFound); });
  it("EQUIP-IDOR-02 treats a foreign Position UUID as not found for all Position operations", async () => { const a = await fixture(); const b = await fixture(); const foreignEquipment = await b.equipment.createEquipment({ context: b.context, name: "foreign" }); const foreignPosition = await b.equipment.createPosition({ context: b.context, equipmentId: foreignEquipment.id, positionCode: "P", name: "foreign" }); for (const operation of [() => a.equipment.getPosition({ context: a.context, positionId: foreignPosition.id }), () => a.equipment.updatePosition({ context: a.context, positionId: foreignPosition.id, name: "no" }), () => a.equipment.setPositionStatus({ context: a.context, positionId: foreignPosition.id, status: "INACTIVE" })]) await expect(operation()).rejects.toMatchObject(notFound); });
  it("EQUIP-NORMALIZATION-01 stores PostgreSQL upper(btrim(positionCode)) for a non-ASCII Position code", async () => { const s = await fixture(); const e = await s.equipment.createEquipment({ context: s.context, name: "A" }); const p = await s.equipment.createPosition({ context: s.context, equipmentId: e.id, positionCode: " ß-slot ", name: "P" }); const rows = await prisma.$queryRaw<Array<{ positionCode: string; normalizedPositionCode: string; databaseNormalized: string }>>`SELECT "positionCode", "normalizedPositionCode", upper(btrim("positionCode")) AS "databaseNormalized" FROM equipment_position WHERE id = ${p.id}::uuid`; expect(rows[0]).toMatchObject({ normalizedPositionCode: "SS-SLOT", databaseNormalized: "SS-SLOT" }); });
});
