import { Prisma, type PrismaClient } from "@prisma/client";
import { createTransactionBoundAuditRecorder, type AuditEvent } from "@/platform/audit";
import { type JsonObject } from "@/platform/errors";
import type { RequestContext } from "@/platform/request-context";
import type { NumberingService } from "@/platform/numbering";
import { equipmentError } from "../application/errors";
import { assertEquipmentStatus, assertPositionStatus, equipmentNumberingPolicy, isUuid, optionalText, positionCode, requiredText, type EquipmentDto, type EquipmentPositionDto, type EquipmentService, type EquipmentStatus, type EquipmentPositionStatus, type Page } from "../domain/equipment";

type Tx = Prisma.TransactionClient;
function user(context: RequestContext) { if (context.actor.kind !== "user") throw equipmentError("INVALID_EQUIPMENT_INPUT"); return context.actor; }
function eventData(event: AuditEvent): Prisma.AuditLogUncheckedCreateInput { return { organizationId: event.organizationId, actorKind: event.actorKind, actorAccountId: event.actorKind === "USER" ? event.actorAccountId : null, actorSessionId: event.actorKind === "USER" ? event.actorSessionId : null, requestId: event.requestId, action: event.action, targetType: event.targetType, targetId: event.targetId, details: event.details as Prisma.InputJsonValue, occurredAt: event.occurredAt }; }
function audit(tx: Tx) { return createTransactionBoundAuditRecorder(async (event) => { await tx.auditLog.create({ data: eventData(event) }); }); }
function dto(row: { id: string; equipmentNumber: string; name: string; model: string | null; description: string | null; status: EquipmentStatus; createdAt: Date; updatedAt: Date }): EquipmentDto { return { id: row.id, equipmentNumber: row.equipmentNumber, name: row.name, model: row.model, description: row.description, status: row.status, createdAt: row.createdAt, updatedAt: row.updatedAt }; }
function positionDto(row: { id: string; positionCode: string; name: string; description: string | null; status: EquipmentPositionStatus; createdAt: Date; updatedAt: Date }, equipment: EquipmentDto): EquipmentPositionDto { return { id: row.id, positionCode: row.positionCode, name: row.name, description: row.description, status: row.status, equipment: { id: equipment.id, equipmentNumber: equipment.equipmentNumber, name: equipment.name, status: equipment.status }, createdAt: row.createdAt, updatedAt: row.updatedAt }; }
function page(value: number | undefined, fallback: number, max: number): number { if (value === undefined) return fallback; if (!Number.isSafeInteger(value) || value < 1 || value > max) throw equipmentError("INVALID_EQUIPMENT_INPUT"); return value; }
function map(error: unknown): never { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") { const meta = error.meta as { target?: unknown; modelName?: unknown } | undefined; const target = Array.isArray(meta?.target) ? meta.target.map(String).join(",") : String(meta?.target ?? ""); const model = String(meta?.modelName ?? ""); if (model === "EquipmentPosition" || target.includes("normalizedPositionCode") || target.includes("equipment_position_equipment_id_normalized_code_key")) throw equipmentError("EQUIPMENT_POSITION_CODE_CONFLICT", error); if (model === "Equipment" || target.includes("equipmentNumber") || target.includes("equipment_organization_id_equipment_number_key")) throw equipmentError("EQUIPMENT_NUMBER_CONFLICT", error); } throw error; }
async function requireEquipment(client: PrismaClient | Tx, id: string, organizationId: string) { if (!isUuid(id)) throw equipmentError("EQUIPMENT_NOT_FOUND"); const row = await client.equipment.findFirst({ where: { id, organizationId } }); if (!row) throw equipmentError("EQUIPMENT_NOT_FOUND"); return row; }
async function requirePosition(client: PrismaClient | Tx, id: string, organizationId: string) { if (!isUuid(id)) throw equipmentError("POSITION_NOT_FOUND"); const row = await client.equipmentPosition.findFirst({ where: { id, organizationId } }); if (!row) throw equipmentError("POSITION_NOT_FOUND"); return row; }
async function lockEquipment(tx: Tx, id: string, organizationId: string) { if (!isUuid(id)) throw equipmentError("EQUIPMENT_NOT_FOUND"); const rows = await tx.$queryRaw<{ id: string }[]>(Prisma.sql`SELECT id FROM equipment WHERE id = ${id}::uuid AND "organizationId" = ${organizationId}::uuid FOR UPDATE`); if (!rows[0]) throw equipmentError("EQUIPMENT_NOT_FOUND"); }
async function lockPosition(tx: Tx, id: string, organizationId: string) { if (!isUuid(id)) throw equipmentError("POSITION_NOT_FOUND"); const rows = await tx.$queryRaw<{ id: string }[]>(Prisma.sql`SELECT id FROM equipment_position WHERE id = ${id}::uuid AND "organizationId" = ${organizationId}::uuid FOR UPDATE`); if (!rows[0]) throw equipmentError("POSITION_NOT_FOUND"); }
function record(context: RequestContext, action: string, targetType: string, targetId: string, details: JsonObject) { const actor = user(context); return { actorKind: "USER" as const, actorAccountId: actor.userId, actorSessionId: actor.sessionId, organizationId: actor.organizationId, requestId: context.requestId, action, targetType, targetId, details, occurredAt: new Date(context.receivedAt) }; }

export function createEquipmentServiceForPrisma(prisma: PrismaClient, numbering: NumberingService): EquipmentService {
  return {
    async createEquipment(input) { const actor = user(input.context); let name: string; let model: string | null; let description: string | null; try { name = requiredText(input.name, 200, "EQUIPMENT_NAME_INVALID"); model = optionalText(input.model, 200, "EQUIPMENT_MODEL_INVALID"); description = optionalText(input.description, 2000, "EQUIPMENT_DESCRIPTION_INVALID"); } catch (e) { throw equipmentError("INVALID_EQUIPMENT_INPUT", e); } const equipmentNumber = (await numbering.allocate(actor.organizationId, equipmentNumberingPolicy)).formatted; try { const created = await prisma.$transaction(async (tx) => { const row = await tx.equipment.create({ data: { organizationId: actor.organizationId, equipmentNumber, name, model, description, status: "ACTIVE" } }); await audit(tx).record(record(input.context, "equipment.create", "equipment", row.id, { equipmentNumber: row.equipmentNumber, status: row.status })); return row; }); return dto(created); } catch (e) { map(e); } },
    async listEquipment(input) { const actor = user(input.context); if (input.status !== undefined) try { assertEquipmentStatus(input.status); } catch (e) { throw equipmentError("INVALID_EQUIPMENT_INPUT", e); } const current = page(input.page, 1, Number.MAX_SAFE_INTEGER); const pageSize = page(input.pageSize, 25, 100); const offset = (current - 1) * pageSize; if (!Number.isSafeInteger(offset)) throw equipmentError("INVALID_EQUIPMENT_INPUT"); const search = input.search?.trim(); const where = { organizationId: actor.organizationId, ...(input.status ? { status: input.status } : {}), ...(search ? { OR: [{ equipmentNumber: { contains: search, mode: "insensitive" as const } }, { name: { contains: search, mode: "insensitive" as const } }, { model: { contains: search, mode: "insensitive" as const } }] } : {}) }; const [total, rows] = await prisma.$transaction([prisma.equipment.count({ where }), prisma.equipment.findMany({ where, orderBy: [{ equipmentNumber: "asc" }, { id: "asc" }], skip: offset, take: pageSize })]); return { items: rows.map(dto), page: current, pageSize, total } satisfies Page<EquipmentDto>; },
    async getEquipment(input) { const actor = user(input.context); return dto(await requireEquipment(prisma, input.equipmentId, actor.organizationId)); },
    async updateEquipment(input) { const actor = user(input.context); let name: string | undefined; let model: string | null | undefined; let description: string | null | undefined; try { if (input.name !== undefined) name = requiredText(input.name, 200, "EQUIPMENT_NAME_INVALID"); if (input.model !== undefined) model = optionalText(input.model, 200, "EQUIPMENT_MODEL_INVALID"); if (input.description !== undefined) description = optionalText(input.description, 2000, "EQUIPMENT_DESCRIPTION_INVALID"); } catch (e) { throw equipmentError("INVALID_EQUIPMENT_INPUT", e); } const row = await prisma.$transaction(async (tx) => { await lockEquipment(tx, input.equipmentId, actor.organizationId); const existing = await requireEquipment(tx, input.equipmentId, actor.organizationId); const changed = name !== undefined && name !== existing.name || model !== undefined && model !== existing.model || description !== undefined && description !== existing.description; if (!changed) return existing; const updated = await tx.equipment.update({ where: { id: existing.id }, data: { ...(name === undefined ? {} : { name }), ...(model === undefined ? {} : { model }), ...(description === undefined ? {} : { description }) } }); const details: Record<string, unknown> = {}; if (name !== undefined && name !== existing.name) details.name = name; if (model !== undefined && model !== existing.model) details.model = model; if (description !== undefined && description !== existing.description) details.description = description; await audit(tx).record(record(input.context, "equipment.update", "equipment", updated.id, { changed: details as JsonObject })); return updated; }); return dto(row); },
    async setEquipmentStatus(input) { const actor = user(input.context); try { assertEquipmentStatus(input.status); } catch (e) { throw equipmentError("INVALID_EQUIPMENT_INPUT", e); } const row = await prisma.$transaction(async (tx) => { await lockEquipment(tx, input.equipmentId, actor.organizationId); const existing = await requireEquipment(tx, input.equipmentId, actor.organizationId); if (existing.status === input.status) return existing; const updated = await tx.equipment.update({ where: { id: existing.id }, data: { status: input.status } }); await audit(tx).record(record(input.context, "equipment.set_status", "equipment", updated.id, { fromStatus: existing.status, toStatus: updated.status })); return updated; }); return dto(row); },
    async createPosition(input) { const actor = user(input.context); let code: { positionCode: string; normalizedPositionCode: string }; let name: string; let description: string | null; try { code = positionCode(input.positionCode); name = requiredText(input.name, 200, "POSITION_NAME_INVALID"); description = optionalText(input.description, 2000, "POSITION_DESCRIPTION_INVALID"); } catch (e) { throw equipmentError("INVALID_EQUIPMENT_INPUT", e); } try { const row = await prisma.$transaction(async (tx) => { await lockEquipment(tx, input.equipmentId, actor.organizationId); const parent = await requireEquipment(tx, input.equipmentId, actor.organizationId); if (parent.status !== "ACTIVE") throw equipmentError("EQUIPMENT_INACTIVE"); const created = await tx.equipmentPosition.create({ data: { organizationId: actor.organizationId, equipmentId: parent.id, ...code, name, description, status: "ACTIVE" } }); await audit(tx).record(record(input.context, "equipment_position.create", "equipment_position", created.id, { equipmentId: parent.id, positionCode: created.positionCode, status: created.status })); return created; }); return positionDto(row, dto(await requireEquipment(prisma, row.equipmentId, actor.organizationId))); } catch (e) { map(e); } },
    async listPositions(input) { const actor = user(input.context); const parent = dto(await requireEquipment(prisma, input.equipmentId, actor.organizationId)); if (input.status !== undefined) try { assertPositionStatus(input.status); } catch (e) { throw equipmentError("INVALID_EQUIPMENT_INPUT", e); } const current = page(input.page, 1, Number.MAX_SAFE_INTEGER); const pageSize = page(input.pageSize, 25, 100); const offset = (current - 1) * pageSize; if (!Number.isSafeInteger(offset)) throw equipmentError("INVALID_EQUIPMENT_INPUT"); const search = input.search?.trim(); const where = { organizationId: actor.organizationId, equipmentId: input.equipmentId, ...(input.status ? { status: input.status } : {}), ...(search ? { OR: [{ positionCode: { contains: search, mode: "insensitive" as const } }, { name: { contains: search, mode: "insensitive" as const } }] } : {}) }; const [total, rows] = await prisma.$transaction([prisma.equipmentPosition.count({ where }), prisma.equipmentPosition.findMany({ where, orderBy: [{ positionCode: "asc" }, { id: "asc" }], skip: offset, take: pageSize })]); return { items: rows.map((row) => positionDto(row, parent)), page: current, pageSize, total } satisfies Page<EquipmentPositionDto>; },
    async getPosition(input) { const actor = user(input.context); const row = await requirePosition(prisma, input.positionId, actor.organizationId); return positionDto(row, dto(await requireEquipment(prisma, row.equipmentId, actor.organizationId))); },
    async updatePosition(input) { const actor = user(input.context); let code: { positionCode: string; normalizedPositionCode: string } | undefined; let name: string | undefined; let description: string | null | undefined; try { if (input.positionCode !== undefined) code = positionCode(input.positionCode); if (input.name !== undefined) name = requiredText(input.name, 200, "POSITION_NAME_INVALID"); if (input.description !== undefined) description = optionalText(input.description, 2000, "POSITION_DESCRIPTION_INVALID"); } catch (e) { throw equipmentError("INVALID_EQUIPMENT_INPUT", e); } try { const row = await prisma.$transaction(async (tx) => { await lockPosition(tx, input.positionId, actor.organizationId); const existing = await requirePosition(tx, input.positionId, actor.organizationId); const changed = code !== undefined && code.normalizedPositionCode !== existing.normalizedPositionCode || name !== undefined && name !== existing.name || description !== undefined && description !== existing.description; if (!changed) return existing; const updated = await tx.equipmentPosition.update({ where: { id: existing.id }, data: { ...(code ?? {}), ...(name === undefined ? {} : { name }), ...(description === undefined ? {} : { description }) } }); const details: Record<string, unknown> = {}; if (code && code.normalizedPositionCode !== existing.normalizedPositionCode) details.positionCode = code.positionCode; if (name !== undefined && name !== existing.name) details.name = name; if (description !== undefined && description !== existing.description) details.description = description; await audit(tx).record(record(input.context, "equipment_position.update", "equipment_position", updated.id, { equipmentId: existing.equipmentId, changed: details as JsonObject })); return updated; }); return positionDto(row, dto(await requireEquipment(prisma, row.equipmentId, actor.organizationId))); } catch (e) { map(e); } },
    async setPositionStatus(input) { const actor = user(input.context); try { assertPositionStatus(input.status); } catch (e) { throw equipmentError("INVALID_EQUIPMENT_INPUT", e); } const row = await prisma.$transaction(async (tx) => { if (input.status === "ACTIVE") { const before = await requirePosition(tx, input.positionId, actor.organizationId); await lockEquipment(tx, before.equipmentId, actor.organizationId); await lockPosition(tx, input.positionId, actor.organizationId); const parent = await requireEquipment(tx, before.equipmentId, actor.organizationId); const existing = await requirePosition(tx, input.positionId, actor.organizationId); if (existing.status === "ACTIVE") return existing; if (parent.status !== "ACTIVE") throw equipmentError("EQUIPMENT_INACTIVE"); const updated = await tx.equipmentPosition.update({ where: { id: existing.id }, data: { status: "ACTIVE" } }); await audit(tx).record(record(input.context, "equipment_position.set_status", "equipment_position", updated.id, { equipmentId: existing.equipmentId, fromStatus: existing.status, toStatus: updated.status })); return updated; } await lockPosition(tx, input.positionId, actor.organizationId); const existing = await requirePosition(tx, input.positionId, actor.organizationId); if (existing.status === "INACTIVE") return existing; const updated = await tx.equipmentPosition.update({ where: { id: existing.id }, data: { status: "INACTIVE" } }); await audit(tx).record(record(input.context, "equipment_position.set_status", "equipment_position", updated.id, { equipmentId: existing.equipmentId, fromStatus: existing.status, toStatus: updated.status })); return updated; }); return positionDto(row, dto(await requireEquipment(prisma, row.equipmentId, actor.organizationId))); },
  };
}
