import { randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { afterAll, afterEach, describe, expect, it } from "vitest";

import { createPartCategoryServiceForPrisma } from "@/modules/part-category/application/part-category-service";
import { createPartMasterServiceForPrisma } from "@/modules/part-master/application/part-master-service";
import { createAuthorizationServiceForPrisma } from "@/platform/authorization/application/authorization-factory";
import { createTestPrismaClient } from "@/platform/database/prisma-client";
import { createNumberingServiceForPrisma } from "@/platform/numbering/application/numbering-service";
import { createAuthenticatedActor, createRequestContext } from "@/platform/request-context";
import type { Clock } from "@/platform/time";

import { createPartRevisionService } from "./application/part-revision-service";
import { isRowLockQuery } from "./infrastructure/part-revision-lock-detector";
import { createPartRevisionTransactionBoundary } from "./infrastructure/part-revision-transaction-boundary";

const prisma = createTestPrismaClient();
const ids: string[] = [];
const ignoredSubtree = { isOrgUnitInSubtree: async () => false };
const fixedClock: Clock = { now: () => new Date("2026-08-22T12:00:00.000Z") };
const defer = () => { let resolve!: () => void; return { promise: new Promise<void>((done) => { resolve = done; }), resolve }; };
const context = (account: { id: string; organizationId: string; primaryOrgUnitId: string }, clock?: Clock) => createRequestContext({ clock, actor: createAuthenticatedActor({ kind: "user", userId: account.id, sessionId: randomUUID(), organizationId: account.organizationId, organizationUnitId: account.primaryOrgUnitId }) });
async function waitFor(condition: () => Promise<boolean>, label: string) { const end = Date.now() + 15_000; while (!(await condition())) { if (Date.now() > end) throw new Error(`Timed out waiting for ${label}`); await new Promise<void>((done) => setImmediate(done)); } }
function observed(client: typeof prisma, onPid: (pid: number) => void) { const transaction = client.$transaction.bind(client); return new Proxy(client, { get(target, property, receiver) { if (property !== "$transaction") return Reflect.get(target, property, receiver); return async (callback: (tx: never) => Promise<unknown>, options?: unknown) => transaction(async (tx) => { const rows = await tx.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`; onPid(rows[0]!.pid); return callback(tx as never); }, options as never); } }) as typeof prisma; }
function pauseAfterLock(client: typeof prisma, table: "part_master" | "part_revision") {
  const locked = defer(); const resume = defer(); let pid = 0; const transaction = client.$transaction.bind(client);
  const paused = new Proxy(client, { get(target, property, receiver) {
    if (property !== "$transaction") return Reflect.get(target, property, receiver);
    return async (callback: (tx: never) => Promise<unknown>, options?: unknown) => {
      void options;
      return transaction(async (tx) => {
        let didPause = false;
        const transactionProxy = new Proxy(tx, { get(transactionTarget, transactionProperty, transactionReceiver) {
          if (transactionProperty !== "$queryRaw") return Reflect.get(transactionTarget, transactionProperty, transactionReceiver);
          const query = transactionTarget.$queryRaw as unknown as (...args: unknown[]) => Promise<unknown>;
          return async (...args: unknown[]) => {
            const result = await query.apply(transactionTarget, args);
            if (!didPause && isRowLockQuery(args[0], table)) { didPause = true; pid = (await transactionTarget.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`)[0]!.pid; locked.resolve(); await resume.promise; }
            return result;
          };
        } });
        return callback(transactionProxy as never);
      }, { maxWait: 10_000, timeout: 60_000 } as never);
    };
  } }) as typeof prisma;
  return { client: paused, locked, resume, get pid() { return pid; } };
}
async function waitBlockedOne(pid: number, gatePid: number, label: string) { await waitFor(async () => (await prisma.$queryRaw<Array<{ blocked: number[] }>>`SELECT pg_blocking_pids(pid) AS blocked FROM pg_stat_activity WHERE pid = ${pid}`).some((row) => row.blocked.includes(gatePid)), label); }
async function hold(table: "part_master" | "part_revision", id: string) { const gate = createTestPrismaClient(); const held = defer(); const release = defer(); let pid = 0; const promise = gate.$transaction(async (tx) => { pid = (await tx.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`)[0]!.pid; if (table === "part_master") await tx.$queryRaw`SELECT id FROM part_master WHERE id = ${id}::uuid FOR UPDATE`; else await tx.$queryRaw`SELECT id FROM part_revision WHERE id = ${id}::uuid FOR UPDATE`; held.resolve(); await release.promise; }, { maxWait: 10_000, timeout: 60_000 }); await held.promise; return { gate, pid, release, promise }; }
async function waitBlocked(pids: readonly number[], gatePid: number, label: string) { await waitFor(async () => { if (pids.length !== 2) return false; const rows = await prisma.$queryRaw<Array<{ blocked: number[] }>>`SELECT pg_blocking_pids(pid) AS blocked FROM pg_stat_activity WHERE pid IN (${pids[0]}, ${pids[1]})`; return rows.length === 2 && rows.every((row) => row.blocked.includes(gatePid)); }, label); }
function expectOneConcurrencyLoser(results: readonly PromiseSettledResult<unknown>[], internalMessage: string) { expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1); const rejected = results.filter((result): result is PromiseRejectedResult => result.status === "rejected"); expect(rejected).toHaveLength(1); expect(rejected[0]!.reason).toMatchObject({ code: "STATE.CONFLICT", internalMessage }); }
function revisions(client: typeof prisma = prisma, clock: Clock = fixedClock, onPid?: (pid: number) => void) { const database = onPid ? observed(client, onPid) : client; return createPartRevisionService(createPartRevisionTransactionBoundary(database, clock), createAuthorizationServiceForPrisma(database, ignoredSubtree)); }
async function fixture() {
  const suffix = randomUUID().slice(0, 8).toUpperCase(); const organization = await prisma.organization.create({ data: { code: `REV-${suffix}`, name: "Revision test" } }); ids.push(organization.id);
  const root = await prisma.orgUnit.create({ data: { organizationId: organization.id, code: "ROOT", name: "Root", sortOrder: 0 } });
  const account = (username: string) => prisma.account.create({ data: { organizationId: organization.id, primaryOrgUnitId: root.id, username: `${username}-${suffix}`, normalizedUsername: `${username}-${suffix}`.toLowerCase(), displayName: username, passwordHash: "test", status: "ACTIVE" } });
  const engineer = await account("Engineer"); const reviewer = await account("Reviewer"); const admin = await account("Admin"); const inspector = await account("Inspector"); const viewer = await account("Viewer");
  await prisma.accountRoleAssignment.createMany({ data: [{ accountId: engineer.id, organizationId: organization.id, role: "ENGINEER", scopeOrgUnitId: root.id }, { accountId: reviewer.id, organizationId: organization.id, role: "QUALITY_MANAGER", scopeOrgUnitId: root.id }, { accountId: admin.id, organizationId: organization.id, role: "ADMIN", scopeOrgUnitId: root.id }, { accountId: inspector.id, organizationId: organization.id, role: "INSPECTOR", scopeOrgUnitId: root.id }, { accountId: viewer.id, organizationId: organization.id, role: "VIEWER", scopeOrgUnitId: root.id }] });
  const categories = createPartCategoryServiceForPrisma(prisma); const parts = createPartMasterServiceForPrisma(prisma, { categories, numbering: createNumberingServiceForPrisma(prisma) }); const category = await categories.create({ context: context(engineer), name: "Revision category" }); const part = await parts.create({ context: context(engineer), categoryId: category.id, name: "Revision Part", drawingNumber: "REV-1" });
  return { organization, root, engineer, reviewer, admin, inspector, viewer, category, parts, part, revisions: revisions() };
}
async function reviewing(scope: Awaited<ReturnType<typeof fixture>>) { const revision = await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "Initial" }); return scope.revisions.submit({ context: context(scope.engineer), revisionId: revision.id }); }
async function release(scope: Awaited<ReturnType<typeof fixture>>, revision?: { id: string }) { const target = revision ?? await reviewing(scope); await scope.revisions.approve({ context: context(scope.reviewer), revisionId: target.id }); return scope.revisions.release({ context: context(scope.reviewer), revisionId: target.id }); }
async function removeAuditFailureTrigger() { await prisma.$executeRaw`DROP TRIGGER IF EXISTS codex_rev_fail_audit_trigger ON "audit_log"`; await prisma.$executeRaw`DROP FUNCTION IF EXISTS codex_rev_fail_audit()`; }
afterEach(async () => { await removeAuditFailureTrigger(); const organizations = ids.splice(0); if (!organizations.length) return; await prisma.partRevisionReview.deleteMany({ where: { organizationId: { in: organizations } } }); await prisma.partRevision.deleteMany({ where: { organizationId: { in: organizations } } }); await prisma.auditLog.deleteMany({ where: { organizationId: { in: organizations } } }); await prisma.partMaster.deleteMany({ where: { organizationId: { in: organizations } } }); await prisma.partCategory.deleteMany({ where: { organizationId: { in: organizations } } }); await prisma.numberingSequence.deleteMany({ where: { organizationId: { in: organizations } } }); await prisma.accountRoleAssignment.deleteMany({ where: { organizationId: { in: organizations } } }); await prisma.account.deleteMany({ where: { organizationId: { in: organizations } } }); await prisma.orgUnit.deleteMany({ where: { organizationId: { in: organizations } } }); await prisma.organization.deleteMany({ where: { id: { in: organizations } } }); });
afterAll(async () => { await removeAuditFailureTrigger(); await prisma.$disconnect(); });

describe("Slice 2B PostgreSQL acceptance", () => {
  it("REV-DB-01 PartRevision and Review composite Organization foreign keys", async () => { const first = await fixture(); const second = await fixture(); const revision = await first.revisions.create({ context: context(first.engineer), partId: first.part.id, changeSummary: "first" }); await expect(prisma.partRevision.create({ data: { organizationId: first.organization.id, partMasterId: second.part.id, revisionNo: 1, changeSummary: "cross", createdByAccountId: first.engineer.id } })).rejects.toMatchObject({ code: "P2003" }); await expect(prisma.partRevisionReview.create({ data: { organizationId: first.organization.id, partRevisionId: revision.id, reviewerAccountId: second.reviewer.id, decision: "APPROVED", comment: null } })).rejects.toMatchObject({ code: "P2003" }); });
  it("REV-DB-02 revisionNo unique within PartMaster", async () => { const scope = await fixture(); const revision = await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "one" }); await expect(prisma.partRevision.create({ data: { organizationId: scope.organization.id, partMasterId: scope.part.id, revisionNo: revision.revisionNo, changeSummary: "duplicate", createdByAccountId: scope.engineer.id } })).rejects.toMatchObject({ code: "P2002" }); });
  it("REV-DB-03 different PartMasters may both have revisionNo 1", async () => { const scope = await fixture(); const other = await scope.parts.create({ context: context(scope.engineer), categoryId: scope.category.id, name: "Second part", drawingNumber: "REV-2" }); expect([await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "one" }), await scope.revisions.create({ context: context(scope.engineer), partId: other.id, changeSummary: "one" })].map((item) => item.revisionNo)).toEqual([1, 1]); });
  it("REV-DB-04 partial unique permits one non-RELEASED Revision", async () => { const scope = await fixture(); await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "one" }); await expect(scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "two" })).rejects.toMatchObject({ internalMessage: "PART_REVISION_UNRELEASED_EXISTS" }); });
  it("REV-DB-05 concurrent first Revision create has one expected conflict loser", async () => { const scope = await fixture(); const a = createTestPrismaClient(); const b = createTestPrismaClient(); const pids: number[] = []; const gate = await hold("part_master", scope.part.id); try { const run = (client: typeof prisma, summary: string) => revisions(client, fixedClock, (pid) => pids.push(pid)).create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: summary }); const outcomes = [run(a, "a"), run(b, "b")]; await waitBlocked(pids, gate.pid, "first-revision creates"); gate.release.resolve(); expectOneConcurrencyLoser(await Promise.allSettled(outcomes), "PART_REVISION_UNRELEASED_EXISTS"); expect(await prisma.partRevision.findMany({ where: { partMasterId: scope.part.id }, select: { revisionNo: true } })).toEqual([{ revisionNo: 1 }]); } finally { gate.release.resolve(); await Promise.allSettled([gate.promise]); await Promise.all([gate.gate.$disconnect(), a.$disconnect(), b.$disconnect()]); } }, 90_000);
  it("REV-DB-06 concurrent Revision N+1 create has one expected conflict loser", async () => { const scope = await fixture(); await release(scope); const a = createTestPrismaClient(); const b = createTestPrismaClient(); const pids: number[] = []; const gate = await hold("part_master", scope.part.id); try { const run = (client: typeof prisma, summary: string) => revisions(client, fixedClock, (pid) => pids.push(pid)).create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: summary }); const outcomes = [run(a, "a"), run(b, "b")]; await waitBlocked(pids, gate.pid, "next-revision creates"); gate.release.resolve(); expectOneConcurrencyLoser(await Promise.allSettled(outcomes), "PART_REVISION_UNRELEASED_EXISTS"); expect(await prisma.partRevision.findMany({ where: { partMasterId: scope.part.id }, orderBy: { revisionNo: "asc" }, select: { revisionNo: true } })).toEqual([{ revisionNo: 1 }, { revisionNo: 2 }]); } finally { gate.release.resolve(); await Promise.allSettled([gate.promise]); await Promise.all([gate.gate.$disconnect(), a.$disconnect(), b.$disconnect()]); } }, 90_000);
  it("REV-DB-07 production drawing update and first Revision create race at the PartMaster row", async () => { const scope = await fixture(); const writer = pauseAfterLock(createTestPrismaClient(), "part_master"); const categories = createPartCategoryServiceForPrisma(writer.client); const parts = createPartMasterServiceForPrisma(writer.client, { categories, numbering: createNumberingServiceForPrisma(writer.client) }); const createClient = createTestPrismaClient(); const pids: number[] = []; try { const drawingUpdate = parts.update({ context: context(scope.engineer), partId: scope.part.id, drawingNumber: "REV-3" }); await writer.locked.promise; const create = revisions(createClient, fixedClock, (pid) => pids.push(pid)).create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "first" }); await waitFor(async () => pids.length === 1, "first Revision backend PID"); await waitBlockedOne(pids[0]!, writer.pid, "first Revision waiting on drawing update"); writer.resume.resolve(); await expect(drawingUpdate).resolves.toMatchObject({ drawingNumber: "REV-3" }); await expect(create).resolves.toMatchObject({ revisionNo: 1 }); } finally { writer.resume.resolve(); await createClient.$disconnect(); await writer.client.$disconnect(); } }, 90_000);
  it("REV-DB-08 drawingNumber mutation is rejected after any Revision", async () => { const scope = await fixture(); await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "first" }); await expect(scope.parts.update({ context: context(scope.engineer), partId: scope.part.id, drawingNumber: "REV-3" })).rejects.toMatchObject({ internalMessage: "PART_MASTER_DRAWING_NUMBER_LOCKED" }); await expect(prisma.partMaster.update({ where: { id: scope.part.id }, data: { drawingNumber: "raw", normalizedDrawingNumber: "RAW" } })).rejects.toThrow("PART_MASTER_DRAWING_NUMBER_LOCKED"); });
  it("REV-DB-09 INACTIVE PartMaster prevents new Revision creation", async () => { const scope = await fixture(); await scope.parts.setStatus({ context: context(scope.engineer), partId: scope.part.id, status: "INACTIVE" }); await expect(scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "inactive" })).rejects.toMatchObject({ internalMessage: "PART_MASTER_INACTIVE" }); });
  it("REV-DB-10 INACTIVE status commits before submit fresh-read and keeps Revision DRAFT", async () => { const scope = await fixture(); const draft = await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "draft" }); const writer = pauseAfterLock(createTestPrismaClient(), "part_master"); const categories = createPartCategoryServiceForPrisma(writer.client); const parts = createPartMasterServiceForPrisma(writer.client, { categories, numbering: createNumberingServiceForPrisma(writer.client) }); const submitClient = createTestPrismaClient(); const pids: number[] = []; try { const deactivate = parts.setStatus({ context: context(scope.engineer), partId: scope.part.id, status: "INACTIVE" }); await writer.locked.promise; const submit = revisions(submitClient, fixedClock, (pid) => pids.push(pid)).submit({ context: context(scope.engineer), revisionId: draft.id }); await waitFor(async () => pids.length === 1, "submit backend PID"); await waitBlockedOne(pids[0]!, writer.pid, "submit waiting on status writer"); writer.resume.resolve(); await expect(deactivate).resolves.toMatchObject({ status: "INACTIVE" }); await expect(submit).rejects.toMatchObject({ internalMessage: "PART_MASTER_INACTIVE" }); expect((await prisma.partRevision.findUniqueOrThrow({ where: { id: draft.id } })).status).toBe("DRAFT"); } finally { writer.resume.resolve(); await submitClient.$disconnect(); await writer.client.$disconnect(); } }, 90_000);
  it("REV-DB-11 update commits new summary before submit continues from the Revision lock", async () => { const scope = await fixture(); const draft = await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "before" }); const writer = pauseAfterLock(createTestPrismaClient(), "part_revision"); const submitClient = createTestPrismaClient(); const pids: number[] = []; try { const update = revisions(writer.client).update({ context: context(scope.engineer), revisionId: draft.id, changeSummary: "after" }); await writer.locked.promise; const submit = revisions(submitClient, fixedClock, (pid) => pids.push(pid)).submit({ context: context(scope.engineer), revisionId: draft.id }); await waitFor(async () => pids.length === 1, "submit backend PID"); await waitBlockedOne(pids[0]!, writer.pid, "submit waiting on Revision update"); writer.resume.resolve(); await update; await submit; await expect(prisma.partRevision.findUniqueOrThrow({ where: { id: draft.id } })).resolves.toMatchObject({ status: "REVIEWING", changeSummary: "after" }); } finally { writer.resume.resolve(); await submitClient.$disconnect(); await writer.client.$disconnect(); } }, 90_000);
  it("REV-DB-12 APPROVE and RETURN have one expected transition conflict loser", async () => { const scope = await fixture(); const revision = await reviewing(scope); const a = createTestPrismaClient(); const b = createTestPrismaClient(); const pids: number[] = []; const gate = await hold("part_revision", revision.id); try { const left = revisions(a, fixedClock, (pid) => pids.push(pid)).approve({ context: context(scope.reviewer), revisionId: revision.id }); const right = revisions(b, fixedClock, (pid) => pids.push(pid)).returnForReview({ context: context(scope.reviewer), revisionId: revision.id, comment: "return" }); await waitBlocked(pids, gate.pid, "decision Revision wait"); gate.release.resolve(); expectOneConcurrencyLoser(await Promise.allSettled([left, right]), "PART_REVISION_INVALID_TRANSITION"); const final = await prisma.partRevision.findUniqueOrThrow({ where: { id: revision.id } }); expect(["APPROVED", "RETURNED"]).toContain(final.status); expect(await prisma.partRevisionReview.count({ where: { partRevisionId: revision.id } })).toBe(1); expect(await prisma.auditLog.count({ where: { targetId: revision.id, action: { in: ["part_revision.approve", "part_revision.return"] } } })).toBe(1); } finally { gate.release.resolve(); await Promise.allSettled([gate.promise]); await Promise.all([gate.gate.$disconnect(), a.$disconnect(), b.$disconnect()]); } }, 90_000);
  it("REV-DB-13 RETURN status, Review and Audit are atomic", async () => { const scope = await fixture(); const revision = await reviewing(scope); await scope.revisions.returnForReview({ context: context(scope.reviewer), revisionId: revision.id, comment: "reason" }); const review = await prisma.partRevisionReview.findFirstOrThrow({ where: { partRevisionId: revision.id } }); const audit = await prisma.auditLog.findFirstOrThrow({ where: { targetId: revision.id, action: "part_revision.return" } }); expect(audit.details).toMatchObject({ reviewId: review.id, toStatus: "RETURNED" }); });
  it("REV-DB-14 APPROVE status, Review and Audit are atomic", async () => { const scope = await fixture(); const revision = await reviewing(scope); await scope.revisions.approve({ context: context(scope.reviewer), revisionId: revision.id }); expect(await prisma.partRevisionReview.count({ where: { partRevisionId: revision.id } })).toBe(1); expect(await prisma.auditLog.count({ where: { targetId: revision.id, action: "part_revision.approve" } })).toBe(1); });
  it("REV-DB-15 forced Audit failure rolls transition and Review back", async () => { const scope = await fixture(); const revision = await reviewing(scope); await removeAuditFailureTrigger(); await prisma.$executeRaw(Prisma.sql`CREATE OR REPLACE FUNCTION codex_rev_fail_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."requestId" = 'rev-audit-fail' THEN RAISE EXCEPTION 'rev-audit-fail'; END IF; RETURN NEW; END; $$`); await prisma.$executeRaw(Prisma.sql`CREATE TRIGGER codex_rev_fail_audit_trigger BEFORE INSERT ON "audit_log" FOR EACH ROW EXECUTE FUNCTION codex_rev_fail_audit()`); try { await expect(scope.revisions.approve({ context: { ...context(scope.reviewer), requestId: "rev-audit-fail" as never }, revisionId: revision.id })).rejects.toThrow("rev-audit-fail"); } finally { await removeAuditFailureTrigger(); } expect((await prisma.partRevision.findUniqueOrThrow({ where: { id: revision.id } })).status).toBe("REVIEWING"); expect(await prisma.partRevisionReview.count({ where: { partRevisionId: revision.id } })).toBe(0); });
  it("REV-DB-16 RELEASE metadata and Audit are atomic", async () => { const scope = await fixture(); const released = await release(scope); const audit = await prisma.auditLog.findFirstOrThrow({ where: { targetId: released.id, action: "part_revision.release" } }); expect(released).toMatchObject({ status: "RELEASED", releasedBy: { id: scope.reviewer.id }, releasedAt: new Date("2026-08-22T12:00:00.000Z") }); expect(audit.details).toMatchObject({ releasedAt: "2026-08-22T12:00:00.000Z" }); });
  it("REV-DB-17 RELEASED Revision cannot mutate or transition", async () => { const scope = await fixture(); const revision = await release(scope); await expect(scope.revisions.update({ context: context(scope.engineer), revisionId: revision.id, changeSummary: "mutate" })).rejects.toMatchObject({ internalMessage: "PART_REVISION_INVALID_TRANSITION" }); await expect(scope.revisions.submit({ context: context(scope.engineer), revisionId: revision.id })).rejects.toMatchObject({ internalMessage: "PART_REVISION_INVALID_TRANSITION" }); });
  it("REV-DB-18 return and resubmit cycles preserve every Review", async () => { const scope = await fixture(); const revision = await reviewing(scope); await scope.revisions.returnForReview({ context: context(scope.reviewer), revisionId: revision.id, comment: "first" }); await scope.revisions.submit({ context: context(scope.engineer), revisionId: revision.id }); await scope.revisions.returnForReview({ context: context(scope.reviewer), revisionId: revision.id, comment: "second" }); expect(await prisma.partRevisionReview.count({ where: { partRevisionId: revision.id } })).toBe(2); });
  it("REV-DB-19 ordinary creator review changes no state, Review or Audit", async () => { const scope = await fixture(); const revision = await reviewing(scope); const before = await prisma.auditLog.count({ where: { targetId: revision.id } }); await expect(scope.revisions.approve({ context: context(scope.engineer), revisionId: revision.id })).rejects.toMatchObject({ internalMessage: "PART_REVISION_CREATOR_REVIEW_FORBIDDEN" }); expect((await prisma.partRevision.findUniqueOrThrow({ where: { id: revision.id } })).status).toBe("REVIEWING"); expect(await prisma.partRevisionReview.count({ where: { partRevisionId: revision.id } })).toBe(0); expect(await prisma.auditLog.count({ where: { targetId: revision.id } })).toBe(before); });
  it("REV-DB-20 ADMIN creator override requires reason and atomically writes Review, state and Audit", async () => { const scope = await fixture(); const revision = await scope.revisions.create({ context: context(scope.admin), partId: scope.part.id, changeSummary: "admin authored" }); await scope.revisions.submit({ context: context(scope.admin), revisionId: revision.id }); await expect(scope.revisions.approve({ context: context(scope.admin), revisionId: revision.id, overrideCreatorReview: true })).rejects.toMatchObject({ code: "PLATFORM.VALIDATION_FAILED" }); await scope.revisions.approve({ context: context(scope.admin), revisionId: revision.id, overrideCreatorReview: true, overrideReason: "Emergency coverage" }); await expect(prisma.partRevisionReview.findFirstOrThrow({ where: { partRevisionId: revision.id } })).resolves.toMatchObject({ creatorReviewOverride: true, overrideReason: "Emergency coverage" }); await expect(prisma.auditLog.findFirstOrThrow({ where: { targetId: revision.id, action: "part_revision.approve" } })).resolves.toMatchObject({ reason: "Emergency coverage" }); });
  it("PostgreSQL lock-evidence helper sanity check", async () => { const rows = await prisma.$queryRaw<Array<{ locks: boolean; activity: boolean }>>`SELECT to_regclass('pg_catalog.pg_locks') IS NOT NULL AS locks, to_regclass('pg_catalog.pg_stat_activity') IS NOT NULL AS activity`; expect(rows[0]).toEqual({ locks: true, activity: true }); });
  it("REV-DB-CONSTRAINTS rejects NULL/blank override and RETURN comment while allowing APPROVED NULL comment", async () => { const scope = await fixture(); const revision = await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "constraints" }); const attempt = (data: Parameters<typeof prisma.partRevisionReview.create>[0]["data"]) => prisma.partRevisionReview.create({ data }); const base = { organizationId: scope.organization.id, partRevisionId: revision.id, reviewerAccountId: scope.reviewer.id, decidedAt: fixedClock.now() }; await expect(attempt({ ...base, decision: "APPROVED", comment: null, creatorReviewOverride: true, overrideReason: null })).rejects.toThrow(); await expect(attempt({ ...base, decision: "APPROVED", comment: null, creatorReviewOverride: true, overrideReason: "   " })).rejects.toThrow(); await expect(attempt({ ...base, decision: "RETURNED", comment: null, creatorReviewOverride: false, overrideReason: null })).rejects.toThrow(); await expect(attempt({ ...base, decision: "RETURNED", comment: "   ", creatorReviewOverride: false, overrideReason: null })).rejects.toThrow(); await expect(attempt({ ...base, decision: "APPROVED", comment: null, creatorReviewOverride: false, overrideReason: null })).resolves.toBeTruthy(); });
  it("REV-CLOCK-01 takes lastSubmittedAt from the Clock after the PartMaster lock, not request arrival", async () => { const scope = await fixture(); const draft = await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "clock" }); let mutationAt = new Date("2026-08-22T12:00:00.000Z"); const lifecycleClock: Clock = { now: () => mutationAt }; const gate = await hold("part_master", scope.part.id); const requestClock: Clock = { now: () => new Date("2026-08-20T12:00:00.000Z") }; const submit = revisions(prisma, lifecycleClock).submit({ context: context(scope.engineer, requestClock), revisionId: draft.id }); try { await waitFor(async () => (await prisma.$queryRaw<Array<{ blocked: number[] }>>`SELECT pg_blocking_pids(pid) AS blocked FROM pg_stat_activity WHERE pid <> ${gate.pid}`).some((row) => row.blocked.includes(gate.pid)), "Clock test PartMaster wait"); mutationAt = new Date("2026-08-22T12:05:00.000Z"); gate.release.resolve(); await submit; expect((await prisma.partRevision.findUniqueOrThrow({ where: { id: draft.id } })).lastSubmittedAt).toEqual(mutationAt); } finally { gate.release.resolve(); await Promise.allSettled([gate.promise]); await gate.gate.$disconnect(); } }, 90_000);
  it("REV-API-IDOR-01 real service calls hide cross-Organization Part and Revision UUIDs", async () => { const first = await fixture(); const second = await fixture(); const revision = await first.revisions.create({ context: context(first.engineer), partId: first.part.id, changeSummary: "private" }); await expect(second.revisions.list({ context: context(second.engineer), partId: first.part.id })).rejects.toMatchObject({ code: "RESOURCE.NOT_FOUND" }); await expect(second.revisions.get({ context: context(second.reviewer), revisionId: revision.id })).rejects.toMatchObject({ code: "RESOURCE.NOT_FOUND" }); await expect(second.revisions.listReviews({ context: context(second.reviewer), revisionId: revision.id })).rejects.toMatchObject({ code: "RESOURCE.NOT_FOUND" }); await expect(second.revisions.update({ context: context(second.engineer), revisionId: revision.id, changeSummary: "attack" })).rejects.toMatchObject({ code: "RESOURCE.NOT_FOUND" }); });
  it("REV-AUDIT-CREATE, UPDATE, SUBMIT and NOOP commit exact Audit facts", async () => { const scope = await fixture(); const created = await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "initial" }); expect(await prisma.auditLog.count({ where: { targetId: created.id, action: "part_revision.create" } })).toBe(1); await scope.revisions.update({ context: context(scope.engineer), revisionId: created.id, changeSummary: "changed" }); await expect(prisma.auditLog.findFirstOrThrow({ where: { targetId: created.id, action: "part_revision.update" } })).resolves.toMatchObject({ details: { changed: { changeSummary: "changed" } } }); const beforeNoop = await prisma.auditLog.count({ where: { targetId: created.id } }); await scope.revisions.update({ context: context(scope.engineer), revisionId: created.id, changeSummary: "changed" }); expect(await prisma.auditLog.count({ where: { targetId: created.id } })).toBe(beforeNoop); await scope.revisions.submit({ context: context(scope.engineer), revisionId: created.id }); await expect(prisma.partRevision.findUniqueOrThrow({ where: { id: created.id } })).resolves.toMatchObject({ status: "REVIEWING", lastSubmittedAt: fixedClock.now() }); expect(await prisma.auditLog.count({ where: { targetId: created.id, action: "part_revision.submit_review" } })).toBe(1); });
  it("REV-API-IDOR-02 cross-Organization valid IDs are 404 for every Revision operation", async () => { const first = await fixture(); const second = await fixture(); const revision = await first.revisions.create({ context: context(first.engineer), partId: first.part.id, changeSummary: "private" }); const other = second.revisions; const otherContext = context(second.reviewer); for (const operation of [() => other.get({ context: otherContext, revisionId: revision.id }), () => other.update({ context: context(second.engineer), revisionId: revision.id, changeSummary: "attack" }), () => other.submit({ context: context(second.engineer), revisionId: revision.id }), () => other.returnForReview({ context: otherContext, revisionId: revision.id, comment: "attack" }), () => other.approve({ context: otherContext, revisionId: revision.id }), () => other.release({ context: otherContext, revisionId: revision.id }), () => other.listReviews({ context: otherContext, revisionId: revision.id }), () => other.list({ context: context(second.engineer), partId: first.part.id }), () => other.create({ context: context(second.engineer), partId: first.part.id, changeSummary: "attack" })]) await expect(operation()).rejects.toMatchObject({ code: "RESOURCE.NOT_FOUND" }); });
  it("REV-TRANSITIONS-01 returns STATE.CONFLICT for illegal workflow writes including RELEASED", async () => { const scope = await fixture(); const draft = await scope.revisions.create({ context: context(scope.engineer), partId: scope.part.id, changeSummary: "draft" }); const reviewer = context(scope.reviewer); await expect(scope.revisions.approve({ context: reviewer, revisionId: draft.id })).rejects.toMatchObject({ code: "STATE.CONFLICT" }); await expect(scope.revisions.release({ context: reviewer, revisionId: draft.id })).rejects.toMatchObject({ code: "STATE.CONFLICT" }); const reviewingRevision = await scope.revisions.submit({ context: context(scope.engineer), revisionId: draft.id }); await expect(scope.revisions.release({ context: reviewer, revisionId: reviewingRevision.id })).rejects.toMatchObject({ code: "STATE.CONFLICT" }); await scope.revisions.approve({ context: reviewer, revisionId: reviewingRevision.id }); await expect(scope.revisions.submit({ context: context(scope.engineer), revisionId: reviewingRevision.id })).rejects.toMatchObject({ code: "STATE.CONFLICT" }); await expect(scope.revisions.returnForReview({ context: reviewer, revisionId: reviewingRevision.id, comment: "late" })).rejects.toMatchObject({ code: "STATE.CONFLICT" }); const released = await scope.revisions.release({ context: reviewer, revisionId: reviewingRevision.id }); for (const operation of [() => scope.revisions.update({ context: context(scope.engineer), revisionId: released.id, changeSummary: "late" }), () => scope.revisions.submit({ context: context(scope.engineer), revisionId: released.id }), () => scope.revisions.returnForReview({ context: reviewer, revisionId: released.id, comment: "late" }), () => scope.revisions.approve({ context: reviewer, revisionId: released.id }), () => scope.revisions.release({ context: reviewer, revisionId: released.id })]) await expect(operation()).rejects.toMatchObject({ code: "STATE.CONFLICT" }); });
  it("REV-AUTH-01 VIEWER, INSPECTOR and ENGINEER get 403 before a Review target can be read", async () => { const scope = await fixture(); const revision = await reviewing(scope); for (const actor of [scope.viewer, scope.inspector, scope.engineer]) await expect(scope.revisions.approve({ context: context(actor), revisionId: revision.id })).rejects.toMatchObject({ code: "AUTH.PERMISSION_DENIED" }); });
});
